// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kmemo/internal/storage/models"
)

func newCardSRS(db *gorm.DB, opts ...gen.DOOption) cardSRS {
	_cardSRS := cardSRS{}

	_cardSRS.cardSRSDo.UseDB(db, opts...)
	_cardSRS.cardSRSDo.UseModel(&models.CardSRS{})

	tableName := _cardSRS.cardSRSDo.TableName()
	_cardSRS.ALL = field.NewAsterisk(tableName)
	_cardSRS.CardID = field.NewString(tableName, "card_id")
	_cardSRS.FSRSState = field.NewString(tableName, "fsrs_state")
	_cardSRS.DueAt = field.NewTime(tableName, "due_at")
	_cardSRS.LastReviewAt = field.NewTime(tableName, "last_review_at")
	_cardSRS.Stability = field.NewFloat64(tableName, "stability")
	_cardSRS.Difficulty = field.NewFloat64(tableName, "difficulty")
	_cardSRS.ElapsedDays = field.NewFloat64(tableName, "elapsed_days")
	_cardSRS.ScheduledDays = field.NewFloat64(tableName, "scheduled_days")
	_cardSRS.Reps = field.NewInt(tableName, "reps")
	_cardSRS.Lapses = field.NewInt(tableName, "lapses")
	_cardSRS.LearningStepsJSON = field.NewString(tableName, "learning_steps_json")
	_cardSRS.Suspended = field.NewBool(tableName, "suspended")
	_cardSRS.CreatedAt = field.NewTime(tableName, "created_at")
	_cardSRS.UpdatedAt = field.NewTime(tableName, "updated_at")
	_cardSRS.Card = cardSRSBelongsToCard{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Card", "models.Card"),
		Knowledge: struct {
			field.RelationField
			Parent struct {
				field.RelationField
			}
			FSRSPreset struct {
				field.RelationField
			}
			Children struct {
				field.RelationField
			}
			SourceDocuments struct {
				field.RelationField
				Knowledge struct {
					field.RelationField
				}
				Cards struct {
					field.RelationField
				}
			}
			Cards struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Card.Knowledge", "models.Knowledge"),
			Parent: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.Knowledge.Parent", "models.Knowledge"),
			},
			FSRSPreset: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.Knowledge.FSRSPreset", "models.FSRSParameter"),
			},
			Children: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.Knowledge.Children", "models.Knowledge"),
			},
			SourceDocuments: struct {
				field.RelationField
				Knowledge struct {
					field.RelationField
				}
				Cards struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Card.Knowledge.SourceDocuments", "models.SourceDocument"),
				Knowledge: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Card.Knowledge.SourceDocuments.Knowledge", "models.Knowledge"),
				},
				Cards: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Card.Knowledge.SourceDocuments.Cards", "models.Card"),
				},
			},
			Cards: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.Knowledge.Cards", "models.Card"),
			},
		},
		SourceDocument: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Card.SourceDocument", "models.SourceDocument"),
		},
		Parent: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Card.Parent", "models.Card"),
		},
		CoverAsset: struct {
			field.RelationField
			Card struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Card.CoverAsset", "models.Asset"),
			Card: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.CoverAsset.Card", "models.Card"),
			},
		},
		SRS: struct {
			field.RelationField
			Card struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Card.SRS", "models.CardSRS"),
			Card: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.SRS.Card", "models.Card"),
			},
		},
		Children: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Card.Children", "models.Card"),
		},
		Assets: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Card.Assets", "models.Asset"),
		},
		CardTags: struct {
			field.RelationField
			Card struct {
				field.RelationField
			}
			Tag struct {
				field.RelationField
				CardTags struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Card.CardTags", "models.CardTag"),
			Card: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.CardTags.Card", "models.Card"),
			},
			Tag: struct {
				field.RelationField
				CardTags struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Card.CardTags.Tag", "models.Tag"),
				CardTags: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Card.CardTags.Tag.CardTags", "models.CardTag"),
				},
			},
		},
	}

	_cardSRS.fillFieldMap()

	return _cardSRS
}

type cardSRS struct {
	cardSRSDo cardSRSDo

	ALL               field.Asterisk
	CardID            field.String
	FSRSState         field.String
	DueAt             field.Time
	LastReviewAt      field.Time
	Stability         field.Float64
	Difficulty        field.Float64
	ElapsedDays       field.Float64
	ScheduledDays     field.Float64
	Reps              field.Int
	Lapses            field.Int
	LearningStepsJSON field.String
	Suspended         field.Bool
	CreatedAt         field.Time
	UpdatedAt         field.Time
	Card              cardSRSBelongsToCard

	fieldMap map[string]field.Expr
}

func (c cardSRS) Table(newTableName string) *cardSRS {
	c.cardSRSDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cardSRS) As(alias string) *cardSRS {
	c.cardSRSDo.DO = *(c.cardSRSDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cardSRS) updateTableName(table string) *cardSRS {
	c.ALL = field.NewAsterisk(table)
	c.CardID = field.NewString(table, "card_id")
	c.FSRSState = field.NewString(table, "fsrs_state")
	c.DueAt = field.NewTime(table, "due_at")
	c.LastReviewAt = field.NewTime(table, "last_review_at")
	c.Stability = field.NewFloat64(table, "stability")
	c.Difficulty = field.NewFloat64(table, "difficulty")
	c.ElapsedDays = field.NewFloat64(table, "elapsed_days")
	c.ScheduledDays = field.NewFloat64(table, "scheduled_days")
	c.Reps = field.NewInt(table, "reps")
	c.Lapses = field.NewInt(table, "lapses")
	c.LearningStepsJSON = field.NewString(table, "learning_steps_json")
	c.Suspended = field.NewBool(table, "suspended")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *cardSRS) WithContext(ctx context.Context) ICardSRSDo { return c.cardSRSDo.WithContext(ctx) }

func (c cardSRS) TableName() string { return c.cardSRSDo.TableName() }

func (c cardSRS) Alias() string { return c.cardSRSDo.Alias() }

func (c cardSRS) Columns(cols ...field.Expr) gen.Columns { return c.cardSRSDo.Columns(cols...) }

func (c *cardSRS) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cardSRS) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 15)
	c.fieldMap["card_id"] = c.CardID
	c.fieldMap["fsrs_state"] = c.FSRSState
	c.fieldMap["due_at"] = c.DueAt
	c.fieldMap["last_review_at"] = c.LastReviewAt
	c.fieldMap["stability"] = c.Stability
	c.fieldMap["difficulty"] = c.Difficulty
	c.fieldMap["elapsed_days"] = c.ElapsedDays
	c.fieldMap["scheduled_days"] = c.ScheduledDays
	c.fieldMap["reps"] = c.Reps
	c.fieldMap["lapses"] = c.Lapses
	c.fieldMap["learning_steps_json"] = c.LearningStepsJSON
	c.fieldMap["suspended"] = c.Suspended
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt

}

func (c cardSRS) clone(db *gorm.DB) cardSRS {
	c.cardSRSDo.ReplaceConnPool(db.Statement.ConnPool)
	c.Card.db = db.Session(&gorm.Session{Initialized: true})
	c.Card.db.Statement.ConnPool = db.Statement.ConnPool
	return c
}

func (c cardSRS) replaceDB(db *gorm.DB) cardSRS {
	c.cardSRSDo.ReplaceDB(db)
	c.Card.db = db.Session(&gorm.Session{})
	return c
}

type cardSRSBelongsToCard struct {
	db *gorm.DB

	field.RelationField

	Knowledge struct {
		field.RelationField
		Parent struct {
			field.RelationField
		}
		FSRSPreset struct {
			field.RelationField
		}
		Children struct {
			field.RelationField
		}
		SourceDocuments struct {
			field.RelationField
			Knowledge struct {
				field.RelationField
			}
			Cards struct {
				field.RelationField
			}
		}
		Cards struct {
			field.RelationField
		}
	}
	SourceDocument struct {
		field.RelationField
	}
	Parent struct {
		field.RelationField
	}
	CoverAsset struct {
		field.RelationField
		Card struct {
			field.RelationField
		}
	}
	SRS struct {
		field.RelationField
		Card struct {
			field.RelationField
		}
	}
	Children struct {
		field.RelationField
	}
	Assets struct {
		field.RelationField
	}
	CardTags struct {
		field.RelationField
		Card struct {
			field.RelationField
		}
		Tag struct {
			field.RelationField
			CardTags struct {
				field.RelationField
			}
		}
	}
}

func (a cardSRSBelongsToCard) Where(conds ...field.Expr) *cardSRSBelongsToCard {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a cardSRSBelongsToCard) WithContext(ctx context.Context) *cardSRSBelongsToCard {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a cardSRSBelongsToCard) Session(session *gorm.Session) *cardSRSBelongsToCard {
	a.db = a.db.Session(session)
	return &a
}

func (a cardSRSBelongsToCard) Model(m *models.CardSRS) *cardSRSBelongsToCardTx {
	return &cardSRSBelongsToCardTx{a.db.Model(m).Association(a.Name())}
}

func (a cardSRSBelongsToCard) Unscoped() *cardSRSBelongsToCard {
	a.db = a.db.Unscoped()
	return &a
}

type cardSRSBelongsToCardTx struct{ tx *gorm.Association }

func (a cardSRSBelongsToCardTx) Find() (result *models.Card, err error) {
	return result, a.tx.Find(&result)
}

func (a cardSRSBelongsToCardTx) Append(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a cardSRSBelongsToCardTx) Replace(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a cardSRSBelongsToCardTx) Delete(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a cardSRSBelongsToCardTx) Clear() error {
	return a.tx.Clear()
}

func (a cardSRSBelongsToCardTx) Count() int64 {
	return a.tx.Count()
}

func (a cardSRSBelongsToCardTx) Unscoped() *cardSRSBelongsToCardTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type cardSRSDo struct{ gen.DO }

type ICardSRSDo interface {
	gen.SubQuery
	Debug() ICardSRSDo
	WithContext(ctx context.Context) ICardSRSDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICardSRSDo
	WriteDB() ICardSRSDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICardSRSDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICardSRSDo
	Not(conds ...gen.Condition) ICardSRSDo
	Or(conds ...gen.Condition) ICardSRSDo
	Select(conds ...field.Expr) ICardSRSDo
	Where(conds ...gen.Condition) ICardSRSDo
	Order(conds ...field.Expr) ICardSRSDo
	Distinct(cols ...field.Expr) ICardSRSDo
	Omit(cols ...field.Expr) ICardSRSDo
	Join(table schema.Tabler, on ...field.Expr) ICardSRSDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICardSRSDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICardSRSDo
	Group(cols ...field.Expr) ICardSRSDo
	Having(conds ...gen.Condition) ICardSRSDo
	Limit(limit int) ICardSRSDo
	Offset(offset int) ICardSRSDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICardSRSDo
	Unscoped() ICardSRSDo
	Create(values ...*models.CardSRS) error
	CreateInBatches(values []*models.CardSRS, batchSize int) error
	Save(values ...*models.CardSRS) error
	First() (*models.CardSRS, error)
	Take() (*models.CardSRS, error)
	Last() (*models.CardSRS, error)
	Find() ([]*models.CardSRS, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CardSRS, err error)
	FindInBatches(result *[]*models.CardSRS, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.CardSRS) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICardSRSDo
	Assign(attrs ...field.AssignExpr) ICardSRSDo
	Joins(fields ...field.RelationField) ICardSRSDo
	Preload(fields ...field.RelationField) ICardSRSDo
	FirstOrInit() (*models.CardSRS, error)
	FirstOrCreate() (*models.CardSRS, error)
	FindByPage(offset int, limit int) (result []*models.CardSRS, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICardSRSDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cardSRSDo) Debug() ICardSRSDo {
	return c.withDO(c.DO.Debug())
}

func (c cardSRSDo) WithContext(ctx context.Context) ICardSRSDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cardSRSDo) ReadDB() ICardSRSDo {
	return c.Clauses(dbresolver.Read)
}

func (c cardSRSDo) WriteDB() ICardSRSDo {
	return c.Clauses(dbresolver.Write)
}

func (c cardSRSDo) Session(config *gorm.Session) ICardSRSDo {
	return c.withDO(c.DO.Session(config))
}

func (c cardSRSDo) Clauses(conds ...clause.Expression) ICardSRSDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cardSRSDo) Returning(value interface{}, columns ...string) ICardSRSDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cardSRSDo) Not(conds ...gen.Condition) ICardSRSDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cardSRSDo) Or(conds ...gen.Condition) ICardSRSDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cardSRSDo) Select(conds ...field.Expr) ICardSRSDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cardSRSDo) Where(conds ...gen.Condition) ICardSRSDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cardSRSDo) Order(conds ...field.Expr) ICardSRSDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cardSRSDo) Distinct(cols ...field.Expr) ICardSRSDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cardSRSDo) Omit(cols ...field.Expr) ICardSRSDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cardSRSDo) Join(table schema.Tabler, on ...field.Expr) ICardSRSDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cardSRSDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICardSRSDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cardSRSDo) RightJoin(table schema.Tabler, on ...field.Expr) ICardSRSDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cardSRSDo) Group(cols ...field.Expr) ICardSRSDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cardSRSDo) Having(conds ...gen.Condition) ICardSRSDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cardSRSDo) Limit(limit int) ICardSRSDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cardSRSDo) Offset(offset int) ICardSRSDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cardSRSDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICardSRSDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cardSRSDo) Unscoped() ICardSRSDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cardSRSDo) Create(values ...*models.CardSRS) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cardSRSDo) CreateInBatches(values []*models.CardSRS, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cardSRSDo) Save(values ...*models.CardSRS) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cardSRSDo) First() (*models.CardSRS, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.CardSRS), nil
	}
}

func (c cardSRSDo) Take() (*models.CardSRS, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.CardSRS), nil
	}
}

func (c cardSRSDo) Last() (*models.CardSRS, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.CardSRS), nil
	}
}

func (c cardSRSDo) Find() ([]*models.CardSRS, error) {
	result, err := c.DO.Find()
	return result.([]*models.CardSRS), err
}

func (c cardSRSDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CardSRS, err error) {
	buf := make([]*models.CardSRS, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cardSRSDo) FindInBatches(result *[]*models.CardSRS, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cardSRSDo) Attrs(attrs ...field.AssignExpr) ICardSRSDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cardSRSDo) Assign(attrs ...field.AssignExpr) ICardSRSDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cardSRSDo) Joins(fields ...field.RelationField) ICardSRSDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cardSRSDo) Preload(fields ...field.RelationField) ICardSRSDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cardSRSDo) FirstOrInit() (*models.CardSRS, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.CardSRS), nil
	}
}

func (c cardSRSDo) FirstOrCreate() (*models.CardSRS, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.CardSRS), nil
	}
}

func (c cardSRSDo) FindByPage(offset int, limit int) (result []*models.CardSRS, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cardSRSDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cardSRSDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cardSRSDo) Delete(models ...*models.CardSRS) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cardSRSDo) withDO(do gen.Dao) *cardSRSDo {
	c.DO = *do.(*gen.DO)
	return c
}
