// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kmemo/internal/storage/models"
)

func newCard(db *gorm.DB, opts ...gen.DOOption) card {
	_card := card{}

	_card.cardDo.UseDB(db, opts...)
	_card.cardDo.UseModel(&models.Card{})

	tableName := _card.cardDo.TableName()
	_card.ALL = field.NewAsterisk(tableName)
	_card.ID = field.NewString(tableName, "id")
	_card.KnowledgeID = field.NewString(tableName, "knowledge_id")
	_card.SourceDocumentID = field.NewString(tableName, "source_document_id")
	_card.ParentID = field.NewString(tableName, "parent_id")
	_card.Title = field.NewString(tableName, "title")
	_card.SortOrder = field.NewInt(tableName, "sort_order")
	_card.Path = field.NewString(tableName, "path")
	_card.CardType = field.NewString(tableName, "card_type")
	_card.Slug = field.NewString(tableName, "slug")
	_card.HTMLHash = field.NewString(tableName, "html_hash")
	_card.AnswerHTMLHash = field.NewString(tableName, "answer_html_hash")
	_card.SourceRef = field.NewString(tableName, "source_ref")
	_card.Status = field.NewString(tableName, "status")
	_card.IsRoot = field.NewBool(tableName, "is_root")
	_card.IsExtract = field.NewBool(tableName, "is_extract")
	_card.CreateFromCardID = field.NewString(tableName, "create_from_card_id")
	_card.CoverAssetID = field.NewString(tableName, "cover_asset_id")
	_card.CreatedAt = field.NewTime(tableName, "created_at")
	_card.UpdatedAt = field.NewTime(tableName, "updated_at")
	_card.DeletedAt = field.NewField(tableName, "deleted_at")
	_card.SRS = cardHasOneSRS{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SRS", "models.CardSRS"),
		Card: struct {
			field.RelationField
			Knowledge struct {
				field.RelationField
				Parent struct {
					field.RelationField
				}
				FSRSPreset struct {
					field.RelationField
				}
				Children struct {
					field.RelationField
				}
				SourceDocuments struct {
					field.RelationField
					Knowledge struct {
						field.RelationField
					}
					Cards struct {
						field.RelationField
					}
				}
				Cards struct {
					field.RelationField
				}
			}
			SourceDocument struct {
				field.RelationField
			}
			Parent struct {
				field.RelationField
			}
			CoverAsset struct {
				field.RelationField
				Card struct {
					field.RelationField
				}
			}
			SRS struct {
				field.RelationField
			}
			Children struct {
				field.RelationField
			}
			Assets struct {
				field.RelationField
			}
			CardTags struct {
				field.RelationField
				Card struct {
					field.RelationField
				}
				Tag struct {
					field.RelationField
					CardTags struct {
						field.RelationField
					}
				}
			}
		}{
			RelationField: field.NewRelation("SRS.Card", "models.Card"),
			Knowledge: struct {
				field.RelationField
				Parent struct {
					field.RelationField
				}
				FSRSPreset struct {
					field.RelationField
				}
				Children struct {
					field.RelationField
				}
				SourceDocuments struct {
					field.RelationField
					Knowledge struct {
						field.RelationField
					}
					Cards struct {
						field.RelationField
					}
				}
				Cards struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("SRS.Card.Knowledge", "models.Knowledge"),
				Parent: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SRS.Card.Knowledge.Parent", "models.Knowledge"),
				},
				FSRSPreset: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SRS.Card.Knowledge.FSRSPreset", "models.FSRSParameter"),
				},
				Children: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SRS.Card.Knowledge.Children", "models.Knowledge"),
				},
				SourceDocuments: struct {
					field.RelationField
					Knowledge struct {
						field.RelationField
					}
					Cards struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("SRS.Card.Knowledge.SourceDocuments", "models.SourceDocument"),
					Knowledge: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("SRS.Card.Knowledge.SourceDocuments.Knowledge", "models.Knowledge"),
					},
					Cards: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("SRS.Card.Knowledge.SourceDocuments.Cards", "models.Card"),
					},
				},
				Cards: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SRS.Card.Knowledge.Cards", "models.Card"),
				},
			},
			SourceDocument: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("SRS.Card.SourceDocument", "models.SourceDocument"),
			},
			Parent: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("SRS.Card.Parent", "models.Card"),
			},
			CoverAsset: struct {
				field.RelationField
				Card struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("SRS.Card.CoverAsset", "models.Asset"),
				Card: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SRS.Card.CoverAsset.Card", "models.Card"),
				},
			},
			SRS: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("SRS.Card.SRS", "models.CardSRS"),
			},
			Children: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("SRS.Card.Children", "models.Card"),
			},
			Assets: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("SRS.Card.Assets", "models.Asset"),
			},
			CardTags: struct {
				field.RelationField
				Card struct {
					field.RelationField
				}
				Tag struct {
					field.RelationField
					CardTags struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("SRS.Card.CardTags", "models.CardTag"),
				Card: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SRS.Card.CardTags.Card", "models.Card"),
				},
				Tag: struct {
					field.RelationField
					CardTags struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("SRS.Card.CardTags.Tag", "models.Tag"),
					CardTags: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("SRS.Card.CardTags.Tag.CardTags", "models.CardTag"),
					},
				},
			},
		},
	}

	_card.Children = cardHasManyChildren{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Children", "models.Card"),
	}

	_card.Assets = cardHasManyAssets{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Assets", "models.Asset"),
	}

	_card.CardTags = cardHasManyCardTags{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("CardTags", "models.CardTag"),
	}

	_card.Knowledge = cardBelongsToKnowledge{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Knowledge", "models.Knowledge"),
	}

	_card.SourceDocument = cardBelongsToSourceDocument{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SourceDocument", "models.SourceDocument"),
	}

	_card.Parent = cardBelongsToParent{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Parent", "models.Card"),
	}

	_card.CoverAsset = cardBelongsToCoverAsset{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("CoverAsset", "models.Asset"),
	}

	_card.fillFieldMap()

	return _card
}

type card struct {
	cardDo cardDo

	ALL              field.Asterisk
	ID               field.String
	KnowledgeID      field.String
	SourceDocumentID field.String
	ParentID         field.String
	Title            field.String
	SortOrder        field.Int
	Path             field.String
	CardType         field.String
	Slug             field.String
	HTMLHash         field.String
	AnswerHTMLHash   field.String
	SourceRef        field.String
	Status           field.String
	IsRoot           field.Bool
	IsExtract        field.Bool
	CreateFromCardID field.String
	CoverAssetID     field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field
	SRS              cardHasOneSRS

	Children cardHasManyChildren

	Assets cardHasManyAssets

	CardTags cardHasManyCardTags

	Knowledge cardBelongsToKnowledge

	SourceDocument cardBelongsToSourceDocument

	Parent cardBelongsToParent

	CoverAsset cardBelongsToCoverAsset

	fieldMap map[string]field.Expr
}

func (c card) Table(newTableName string) *card {
	c.cardDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c card) As(alias string) *card {
	c.cardDo.DO = *(c.cardDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *card) updateTableName(table string) *card {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.KnowledgeID = field.NewString(table, "knowledge_id")
	c.SourceDocumentID = field.NewString(table, "source_document_id")
	c.ParentID = field.NewString(table, "parent_id")
	c.Title = field.NewString(table, "title")
	c.SortOrder = field.NewInt(table, "sort_order")
	c.Path = field.NewString(table, "path")
	c.CardType = field.NewString(table, "card_type")
	c.Slug = field.NewString(table, "slug")
	c.HTMLHash = field.NewString(table, "html_hash")
	c.AnswerHTMLHash = field.NewString(table, "answer_html_hash")
	c.SourceRef = field.NewString(table, "source_ref")
	c.Status = field.NewString(table, "status")
	c.IsRoot = field.NewBool(table, "is_root")
	c.IsExtract = field.NewBool(table, "is_extract")
	c.CreateFromCardID = field.NewString(table, "create_from_card_id")
	c.CoverAssetID = field.NewString(table, "cover_asset_id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *card) WithContext(ctx context.Context) ICardDo { return c.cardDo.WithContext(ctx) }

func (c card) TableName() string { return c.cardDo.TableName() }

func (c card) Alias() string { return c.cardDo.Alias() }

func (c card) Columns(cols ...field.Expr) gen.Columns { return c.cardDo.Columns(cols...) }

func (c *card) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *card) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 28)
	c.fieldMap["id"] = c.ID
	c.fieldMap["knowledge_id"] = c.KnowledgeID
	c.fieldMap["source_document_id"] = c.SourceDocumentID
	c.fieldMap["parent_id"] = c.ParentID
	c.fieldMap["title"] = c.Title
	c.fieldMap["sort_order"] = c.SortOrder
	c.fieldMap["path"] = c.Path
	c.fieldMap["card_type"] = c.CardType
	c.fieldMap["slug"] = c.Slug
	c.fieldMap["html_hash"] = c.HTMLHash
	c.fieldMap["answer_html_hash"] = c.AnswerHTMLHash
	c.fieldMap["source_ref"] = c.SourceRef
	c.fieldMap["status"] = c.Status
	c.fieldMap["is_root"] = c.IsRoot
	c.fieldMap["is_extract"] = c.IsExtract
	c.fieldMap["create_from_card_id"] = c.CreateFromCardID
	c.fieldMap["cover_asset_id"] = c.CoverAssetID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt

}

func (c card) clone(db *gorm.DB) card {
	c.cardDo.ReplaceConnPool(db.Statement.ConnPool)
	c.SRS.db = db.Session(&gorm.Session{Initialized: true})
	c.SRS.db.Statement.ConnPool = db.Statement.ConnPool
	c.Children.db = db.Session(&gorm.Session{Initialized: true})
	c.Children.db.Statement.ConnPool = db.Statement.ConnPool
	c.Assets.db = db.Session(&gorm.Session{Initialized: true})
	c.Assets.db.Statement.ConnPool = db.Statement.ConnPool
	c.CardTags.db = db.Session(&gorm.Session{Initialized: true})
	c.CardTags.db.Statement.ConnPool = db.Statement.ConnPool
	c.Knowledge.db = db.Session(&gorm.Session{Initialized: true})
	c.Knowledge.db.Statement.ConnPool = db.Statement.ConnPool
	c.SourceDocument.db = db.Session(&gorm.Session{Initialized: true})
	c.SourceDocument.db.Statement.ConnPool = db.Statement.ConnPool
	c.Parent.db = db.Session(&gorm.Session{Initialized: true})
	c.Parent.db.Statement.ConnPool = db.Statement.ConnPool
	c.CoverAsset.db = db.Session(&gorm.Session{Initialized: true})
	c.CoverAsset.db.Statement.ConnPool = db.Statement.ConnPool
	return c
}

func (c card) replaceDB(db *gorm.DB) card {
	c.cardDo.ReplaceDB(db)
	c.SRS.db = db.Session(&gorm.Session{})
	c.Children.db = db.Session(&gorm.Session{})
	c.Assets.db = db.Session(&gorm.Session{})
	c.CardTags.db = db.Session(&gorm.Session{})
	c.Knowledge.db = db.Session(&gorm.Session{})
	c.SourceDocument.db = db.Session(&gorm.Session{})
	c.Parent.db = db.Session(&gorm.Session{})
	c.CoverAsset.db = db.Session(&gorm.Session{})
	return c
}

type cardHasOneSRS struct {
	db *gorm.DB

	field.RelationField

	Card struct {
		field.RelationField
		Knowledge struct {
			field.RelationField
			Parent struct {
				field.RelationField
			}
			FSRSPreset struct {
				field.RelationField
			}
			Children struct {
				field.RelationField
			}
			SourceDocuments struct {
				field.RelationField
				Knowledge struct {
					field.RelationField
				}
				Cards struct {
					field.RelationField
				}
			}
			Cards struct {
				field.RelationField
			}
		}
		SourceDocument struct {
			field.RelationField
		}
		Parent struct {
			field.RelationField
		}
		CoverAsset struct {
			field.RelationField
			Card struct {
				field.RelationField
			}
		}
		SRS struct {
			field.RelationField
		}
		Children struct {
			field.RelationField
		}
		Assets struct {
			field.RelationField
		}
		CardTags struct {
			field.RelationField
			Card struct {
				field.RelationField
			}
			Tag struct {
				field.RelationField
				CardTags struct {
					field.RelationField
				}
			}
		}
	}
}

func (a cardHasOneSRS) Where(conds ...field.Expr) *cardHasOneSRS {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a cardHasOneSRS) WithContext(ctx context.Context) *cardHasOneSRS {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a cardHasOneSRS) Session(session *gorm.Session) *cardHasOneSRS {
	a.db = a.db.Session(session)
	return &a
}

func (a cardHasOneSRS) Model(m *models.Card) *cardHasOneSRSTx {
	return &cardHasOneSRSTx{a.db.Model(m).Association(a.Name())}
}

func (a cardHasOneSRS) Unscoped() *cardHasOneSRS {
	a.db = a.db.Unscoped()
	return &a
}

type cardHasOneSRSTx struct{ tx *gorm.Association }

func (a cardHasOneSRSTx) Find() (result *models.CardSRS, err error) {
	return result, a.tx.Find(&result)
}

func (a cardHasOneSRSTx) Append(values ...*models.CardSRS) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a cardHasOneSRSTx) Replace(values ...*models.CardSRS) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a cardHasOneSRSTx) Delete(values ...*models.CardSRS) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a cardHasOneSRSTx) Clear() error {
	return a.tx.Clear()
}

func (a cardHasOneSRSTx) Count() int64 {
	return a.tx.Count()
}

func (a cardHasOneSRSTx) Unscoped() *cardHasOneSRSTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type cardHasManyChildren struct {
	db *gorm.DB

	field.RelationField
}

func (a cardHasManyChildren) Where(conds ...field.Expr) *cardHasManyChildren {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a cardHasManyChildren) WithContext(ctx context.Context) *cardHasManyChildren {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a cardHasManyChildren) Session(session *gorm.Session) *cardHasManyChildren {
	a.db = a.db.Session(session)
	return &a
}

func (a cardHasManyChildren) Model(m *models.Card) *cardHasManyChildrenTx {
	return &cardHasManyChildrenTx{a.db.Model(m).Association(a.Name())}
}

func (a cardHasManyChildren) Unscoped() *cardHasManyChildren {
	a.db = a.db.Unscoped()
	return &a
}

type cardHasManyChildrenTx struct{ tx *gorm.Association }

func (a cardHasManyChildrenTx) Find() (result []*models.Card, err error) {
	return result, a.tx.Find(&result)
}

func (a cardHasManyChildrenTx) Append(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a cardHasManyChildrenTx) Replace(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a cardHasManyChildrenTx) Delete(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a cardHasManyChildrenTx) Clear() error {
	return a.tx.Clear()
}

func (a cardHasManyChildrenTx) Count() int64 {
	return a.tx.Count()
}

func (a cardHasManyChildrenTx) Unscoped() *cardHasManyChildrenTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type cardHasManyAssets struct {
	db *gorm.DB

	field.RelationField
}

func (a cardHasManyAssets) Where(conds ...field.Expr) *cardHasManyAssets {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a cardHasManyAssets) WithContext(ctx context.Context) *cardHasManyAssets {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a cardHasManyAssets) Session(session *gorm.Session) *cardHasManyAssets {
	a.db = a.db.Session(session)
	return &a
}

func (a cardHasManyAssets) Model(m *models.Card) *cardHasManyAssetsTx {
	return &cardHasManyAssetsTx{a.db.Model(m).Association(a.Name())}
}

func (a cardHasManyAssets) Unscoped() *cardHasManyAssets {
	a.db = a.db.Unscoped()
	return &a
}

type cardHasManyAssetsTx struct{ tx *gorm.Association }

func (a cardHasManyAssetsTx) Find() (result []*models.Asset, err error) {
	return result, a.tx.Find(&result)
}

func (a cardHasManyAssetsTx) Append(values ...*models.Asset) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a cardHasManyAssetsTx) Replace(values ...*models.Asset) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a cardHasManyAssetsTx) Delete(values ...*models.Asset) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a cardHasManyAssetsTx) Clear() error {
	return a.tx.Clear()
}

func (a cardHasManyAssetsTx) Count() int64 {
	return a.tx.Count()
}

func (a cardHasManyAssetsTx) Unscoped() *cardHasManyAssetsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type cardHasManyCardTags struct {
	db *gorm.DB

	field.RelationField
}

func (a cardHasManyCardTags) Where(conds ...field.Expr) *cardHasManyCardTags {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a cardHasManyCardTags) WithContext(ctx context.Context) *cardHasManyCardTags {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a cardHasManyCardTags) Session(session *gorm.Session) *cardHasManyCardTags {
	a.db = a.db.Session(session)
	return &a
}

func (a cardHasManyCardTags) Model(m *models.Card) *cardHasManyCardTagsTx {
	return &cardHasManyCardTagsTx{a.db.Model(m).Association(a.Name())}
}

func (a cardHasManyCardTags) Unscoped() *cardHasManyCardTags {
	a.db = a.db.Unscoped()
	return &a
}

type cardHasManyCardTagsTx struct{ tx *gorm.Association }

func (a cardHasManyCardTagsTx) Find() (result []*models.CardTag, err error) {
	return result, a.tx.Find(&result)
}

func (a cardHasManyCardTagsTx) Append(values ...*models.CardTag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a cardHasManyCardTagsTx) Replace(values ...*models.CardTag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a cardHasManyCardTagsTx) Delete(values ...*models.CardTag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a cardHasManyCardTagsTx) Clear() error {
	return a.tx.Clear()
}

func (a cardHasManyCardTagsTx) Count() int64 {
	return a.tx.Count()
}

func (a cardHasManyCardTagsTx) Unscoped() *cardHasManyCardTagsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type cardBelongsToKnowledge struct {
	db *gorm.DB

	field.RelationField
}

func (a cardBelongsToKnowledge) Where(conds ...field.Expr) *cardBelongsToKnowledge {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a cardBelongsToKnowledge) WithContext(ctx context.Context) *cardBelongsToKnowledge {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a cardBelongsToKnowledge) Session(session *gorm.Session) *cardBelongsToKnowledge {
	a.db = a.db.Session(session)
	return &a
}

func (a cardBelongsToKnowledge) Model(m *models.Card) *cardBelongsToKnowledgeTx {
	return &cardBelongsToKnowledgeTx{a.db.Model(m).Association(a.Name())}
}

func (a cardBelongsToKnowledge) Unscoped() *cardBelongsToKnowledge {
	a.db = a.db.Unscoped()
	return &a
}

type cardBelongsToKnowledgeTx struct{ tx *gorm.Association }

func (a cardBelongsToKnowledgeTx) Find() (result *models.Knowledge, err error) {
	return result, a.tx.Find(&result)
}

func (a cardBelongsToKnowledgeTx) Append(values ...*models.Knowledge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a cardBelongsToKnowledgeTx) Replace(values ...*models.Knowledge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a cardBelongsToKnowledgeTx) Delete(values ...*models.Knowledge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a cardBelongsToKnowledgeTx) Clear() error {
	return a.tx.Clear()
}

func (a cardBelongsToKnowledgeTx) Count() int64 {
	return a.tx.Count()
}

func (a cardBelongsToKnowledgeTx) Unscoped() *cardBelongsToKnowledgeTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type cardBelongsToSourceDocument struct {
	db *gorm.DB

	field.RelationField
}

func (a cardBelongsToSourceDocument) Where(conds ...field.Expr) *cardBelongsToSourceDocument {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a cardBelongsToSourceDocument) WithContext(ctx context.Context) *cardBelongsToSourceDocument {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a cardBelongsToSourceDocument) Session(session *gorm.Session) *cardBelongsToSourceDocument {
	a.db = a.db.Session(session)
	return &a
}

func (a cardBelongsToSourceDocument) Model(m *models.Card) *cardBelongsToSourceDocumentTx {
	return &cardBelongsToSourceDocumentTx{a.db.Model(m).Association(a.Name())}
}

func (a cardBelongsToSourceDocument) Unscoped() *cardBelongsToSourceDocument {
	a.db = a.db.Unscoped()
	return &a
}

type cardBelongsToSourceDocumentTx struct{ tx *gorm.Association }

func (a cardBelongsToSourceDocumentTx) Find() (result *models.SourceDocument, err error) {
	return result, a.tx.Find(&result)
}

func (a cardBelongsToSourceDocumentTx) Append(values ...*models.SourceDocument) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a cardBelongsToSourceDocumentTx) Replace(values ...*models.SourceDocument) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a cardBelongsToSourceDocumentTx) Delete(values ...*models.SourceDocument) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a cardBelongsToSourceDocumentTx) Clear() error {
	return a.tx.Clear()
}

func (a cardBelongsToSourceDocumentTx) Count() int64 {
	return a.tx.Count()
}

func (a cardBelongsToSourceDocumentTx) Unscoped() *cardBelongsToSourceDocumentTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type cardBelongsToParent struct {
	db *gorm.DB

	field.RelationField
}

func (a cardBelongsToParent) Where(conds ...field.Expr) *cardBelongsToParent {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a cardBelongsToParent) WithContext(ctx context.Context) *cardBelongsToParent {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a cardBelongsToParent) Session(session *gorm.Session) *cardBelongsToParent {
	a.db = a.db.Session(session)
	return &a
}

func (a cardBelongsToParent) Model(m *models.Card) *cardBelongsToParentTx {
	return &cardBelongsToParentTx{a.db.Model(m).Association(a.Name())}
}

func (a cardBelongsToParent) Unscoped() *cardBelongsToParent {
	a.db = a.db.Unscoped()
	return &a
}

type cardBelongsToParentTx struct{ tx *gorm.Association }

func (a cardBelongsToParentTx) Find() (result *models.Card, err error) {
	return result, a.tx.Find(&result)
}

func (a cardBelongsToParentTx) Append(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a cardBelongsToParentTx) Replace(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a cardBelongsToParentTx) Delete(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a cardBelongsToParentTx) Clear() error {
	return a.tx.Clear()
}

func (a cardBelongsToParentTx) Count() int64 {
	return a.tx.Count()
}

func (a cardBelongsToParentTx) Unscoped() *cardBelongsToParentTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type cardBelongsToCoverAsset struct {
	db *gorm.DB

	field.RelationField
}

func (a cardBelongsToCoverAsset) Where(conds ...field.Expr) *cardBelongsToCoverAsset {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a cardBelongsToCoverAsset) WithContext(ctx context.Context) *cardBelongsToCoverAsset {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a cardBelongsToCoverAsset) Session(session *gorm.Session) *cardBelongsToCoverAsset {
	a.db = a.db.Session(session)
	return &a
}

func (a cardBelongsToCoverAsset) Model(m *models.Card) *cardBelongsToCoverAssetTx {
	return &cardBelongsToCoverAssetTx{a.db.Model(m).Association(a.Name())}
}

func (a cardBelongsToCoverAsset) Unscoped() *cardBelongsToCoverAsset {
	a.db = a.db.Unscoped()
	return &a
}

type cardBelongsToCoverAssetTx struct{ tx *gorm.Association }

func (a cardBelongsToCoverAssetTx) Find() (result *models.Asset, err error) {
	return result, a.tx.Find(&result)
}

func (a cardBelongsToCoverAssetTx) Append(values ...*models.Asset) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a cardBelongsToCoverAssetTx) Replace(values ...*models.Asset) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a cardBelongsToCoverAssetTx) Delete(values ...*models.Asset) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a cardBelongsToCoverAssetTx) Clear() error {
	return a.tx.Clear()
}

func (a cardBelongsToCoverAssetTx) Count() int64 {
	return a.tx.Count()
}

func (a cardBelongsToCoverAssetTx) Unscoped() *cardBelongsToCoverAssetTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type cardDo struct{ gen.DO }

type ICardDo interface {
	gen.SubQuery
	Debug() ICardDo
	WithContext(ctx context.Context) ICardDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICardDo
	WriteDB() ICardDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICardDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICardDo
	Not(conds ...gen.Condition) ICardDo
	Or(conds ...gen.Condition) ICardDo
	Select(conds ...field.Expr) ICardDo
	Where(conds ...gen.Condition) ICardDo
	Order(conds ...field.Expr) ICardDo
	Distinct(cols ...field.Expr) ICardDo
	Omit(cols ...field.Expr) ICardDo
	Join(table schema.Tabler, on ...field.Expr) ICardDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICardDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICardDo
	Group(cols ...field.Expr) ICardDo
	Having(conds ...gen.Condition) ICardDo
	Limit(limit int) ICardDo
	Offset(offset int) ICardDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICardDo
	Unscoped() ICardDo
	Create(values ...*models.Card) error
	CreateInBatches(values []*models.Card, batchSize int) error
	Save(values ...*models.Card) error
	First() (*models.Card, error)
	Take() (*models.Card, error)
	Last() (*models.Card, error)
	Find() ([]*models.Card, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Card, err error)
	FindInBatches(result *[]*models.Card, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Card) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICardDo
	Assign(attrs ...field.AssignExpr) ICardDo
	Joins(fields ...field.RelationField) ICardDo
	Preload(fields ...field.RelationField) ICardDo
	FirstOrInit() (*models.Card, error)
	FirstOrCreate() (*models.Card, error)
	FindByPage(offset int, limit int) (result []*models.Card, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICardDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cardDo) Debug() ICardDo {
	return c.withDO(c.DO.Debug())
}

func (c cardDo) WithContext(ctx context.Context) ICardDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cardDo) ReadDB() ICardDo {
	return c.Clauses(dbresolver.Read)
}

func (c cardDo) WriteDB() ICardDo {
	return c.Clauses(dbresolver.Write)
}

func (c cardDo) Session(config *gorm.Session) ICardDo {
	return c.withDO(c.DO.Session(config))
}

func (c cardDo) Clauses(conds ...clause.Expression) ICardDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cardDo) Returning(value interface{}, columns ...string) ICardDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cardDo) Not(conds ...gen.Condition) ICardDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cardDo) Or(conds ...gen.Condition) ICardDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cardDo) Select(conds ...field.Expr) ICardDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cardDo) Where(conds ...gen.Condition) ICardDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cardDo) Order(conds ...field.Expr) ICardDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cardDo) Distinct(cols ...field.Expr) ICardDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cardDo) Omit(cols ...field.Expr) ICardDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cardDo) Join(table schema.Tabler, on ...field.Expr) ICardDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cardDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICardDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cardDo) RightJoin(table schema.Tabler, on ...field.Expr) ICardDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cardDo) Group(cols ...field.Expr) ICardDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cardDo) Having(conds ...gen.Condition) ICardDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cardDo) Limit(limit int) ICardDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cardDo) Offset(offset int) ICardDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cardDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICardDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cardDo) Unscoped() ICardDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cardDo) Create(values ...*models.Card) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cardDo) CreateInBatches(values []*models.Card, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cardDo) Save(values ...*models.Card) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cardDo) First() (*models.Card, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Card), nil
	}
}

func (c cardDo) Take() (*models.Card, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Card), nil
	}
}

func (c cardDo) Last() (*models.Card, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Card), nil
	}
}

func (c cardDo) Find() ([]*models.Card, error) {
	result, err := c.DO.Find()
	return result.([]*models.Card), err
}

func (c cardDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Card, err error) {
	buf := make([]*models.Card, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cardDo) FindInBatches(result *[]*models.Card, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cardDo) Attrs(attrs ...field.AssignExpr) ICardDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cardDo) Assign(attrs ...field.AssignExpr) ICardDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cardDo) Joins(fields ...field.RelationField) ICardDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cardDo) Preload(fields ...field.RelationField) ICardDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cardDo) FirstOrInit() (*models.Card, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Card), nil
	}
}

func (c cardDo) FirstOrCreate() (*models.Card, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Card), nil
	}
}

func (c cardDo) FindByPage(offset int, limit int) (result []*models.Card, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cardDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cardDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cardDo) Delete(models ...*models.Card) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cardDo) withDO(do gen.Dao) *cardDo {
	c.DO = *do.(*gen.DO)
	return c
}
