// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kmemo/internal/storage/models"
)

func newCardTag(db *gorm.DB, opts ...gen.DOOption) cardTag {
	_cardTag := cardTag{}

	_cardTag.cardTagDo.UseDB(db, opts...)
	_cardTag.cardTagDo.UseModel(&models.CardTag{})

	tableName := _cardTag.cardTagDo.TableName()
	_cardTag.ALL = field.NewAsterisk(tableName)
	_cardTag.CardID = field.NewString(tableName, "card_id")
	_cardTag.TagID = field.NewString(tableName, "tag_id")
	_cardTag.CreatedAt = field.NewTime(tableName, "created_at")
	_cardTag.Card = cardTagBelongsToCard{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Card", "models.Card"),
		Knowledge: struct {
			field.RelationField
			Parent struct {
				field.RelationField
			}
			FSRSPreset struct {
				field.RelationField
			}
			Children struct {
				field.RelationField
			}
			SourceDocuments struct {
				field.RelationField
				Knowledge struct {
					field.RelationField
				}
				Cards struct {
					field.RelationField
				}
			}
			Cards struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Card.Knowledge", "models.Knowledge"),
			Parent: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.Knowledge.Parent", "models.Knowledge"),
			},
			FSRSPreset: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.Knowledge.FSRSPreset", "models.FSRSParameter"),
			},
			Children: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.Knowledge.Children", "models.Knowledge"),
			},
			SourceDocuments: struct {
				field.RelationField
				Knowledge struct {
					field.RelationField
				}
				Cards struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Card.Knowledge.SourceDocuments", "models.SourceDocument"),
				Knowledge: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Card.Knowledge.SourceDocuments.Knowledge", "models.Knowledge"),
				},
				Cards: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Card.Knowledge.SourceDocuments.Cards", "models.Card"),
				},
			},
			Cards: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.Knowledge.Cards", "models.Card"),
			},
		},
		SourceDocument: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Card.SourceDocument", "models.SourceDocument"),
		},
		Parent: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Card.Parent", "models.Card"),
		},
		CoverAsset: struct {
			field.RelationField
			Card struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Card.CoverAsset", "models.Asset"),
			Card: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.CoverAsset.Card", "models.Card"),
			},
		},
		SRS: struct {
			field.RelationField
			Card struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Card.SRS", "models.CardSRS"),
			Card: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.SRS.Card", "models.Card"),
			},
		},
		Children: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Card.Children", "models.Card"),
		},
		Assets: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Card.Assets", "models.Asset"),
		},
		CardTags: struct {
			field.RelationField
			Card struct {
				field.RelationField
			}
			Tag struct {
				field.RelationField
				CardTags struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Card.CardTags", "models.CardTag"),
			Card: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.CardTags.Card", "models.Card"),
			},
			Tag: struct {
				field.RelationField
				CardTags struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Card.CardTags.Tag", "models.Tag"),
				CardTags: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Card.CardTags.Tag.CardTags", "models.CardTag"),
				},
			},
		},
	}

	_cardTag.Tag = cardTagBelongsToTag{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Tag", "models.Tag"),
	}

	_cardTag.fillFieldMap()

	return _cardTag
}

type cardTag struct {
	cardTagDo cardTagDo

	ALL       field.Asterisk
	CardID    field.String
	TagID     field.String
	CreatedAt field.Time
	Card      cardTagBelongsToCard

	Tag cardTagBelongsToTag

	fieldMap map[string]field.Expr
}

func (c cardTag) Table(newTableName string) *cardTag {
	c.cardTagDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cardTag) As(alias string) *cardTag {
	c.cardTagDo.DO = *(c.cardTagDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cardTag) updateTableName(table string) *cardTag {
	c.ALL = field.NewAsterisk(table)
	c.CardID = field.NewString(table, "card_id")
	c.TagID = field.NewString(table, "tag_id")
	c.CreatedAt = field.NewTime(table, "created_at")

	c.fillFieldMap()

	return c
}

func (c *cardTag) WithContext(ctx context.Context) ICardTagDo { return c.cardTagDo.WithContext(ctx) }

func (c cardTag) TableName() string { return c.cardTagDo.TableName() }

func (c cardTag) Alias() string { return c.cardTagDo.Alias() }

func (c cardTag) Columns(cols ...field.Expr) gen.Columns { return c.cardTagDo.Columns(cols...) }

func (c *cardTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cardTag) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 5)
	c.fieldMap["card_id"] = c.CardID
	c.fieldMap["tag_id"] = c.TagID
	c.fieldMap["created_at"] = c.CreatedAt

}

func (c cardTag) clone(db *gorm.DB) cardTag {
	c.cardTagDo.ReplaceConnPool(db.Statement.ConnPool)
	c.Card.db = db.Session(&gorm.Session{Initialized: true})
	c.Card.db.Statement.ConnPool = db.Statement.ConnPool
	c.Tag.db = db.Session(&gorm.Session{Initialized: true})
	c.Tag.db.Statement.ConnPool = db.Statement.ConnPool
	return c
}

func (c cardTag) replaceDB(db *gorm.DB) cardTag {
	c.cardTagDo.ReplaceDB(db)
	c.Card.db = db.Session(&gorm.Session{})
	c.Tag.db = db.Session(&gorm.Session{})
	return c
}

type cardTagBelongsToCard struct {
	db *gorm.DB

	field.RelationField

	Knowledge struct {
		field.RelationField
		Parent struct {
			field.RelationField
		}
		FSRSPreset struct {
			field.RelationField
		}
		Children struct {
			field.RelationField
		}
		SourceDocuments struct {
			field.RelationField
			Knowledge struct {
				field.RelationField
			}
			Cards struct {
				field.RelationField
			}
		}
		Cards struct {
			field.RelationField
		}
	}
	SourceDocument struct {
		field.RelationField
	}
	Parent struct {
		field.RelationField
	}
	CoverAsset struct {
		field.RelationField
		Card struct {
			field.RelationField
		}
	}
	SRS struct {
		field.RelationField
		Card struct {
			field.RelationField
		}
	}
	Children struct {
		field.RelationField
	}
	Assets struct {
		field.RelationField
	}
	CardTags struct {
		field.RelationField
		Card struct {
			field.RelationField
		}
		Tag struct {
			field.RelationField
			CardTags struct {
				field.RelationField
			}
		}
	}
}

func (a cardTagBelongsToCard) Where(conds ...field.Expr) *cardTagBelongsToCard {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a cardTagBelongsToCard) WithContext(ctx context.Context) *cardTagBelongsToCard {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a cardTagBelongsToCard) Session(session *gorm.Session) *cardTagBelongsToCard {
	a.db = a.db.Session(session)
	return &a
}

func (a cardTagBelongsToCard) Model(m *models.CardTag) *cardTagBelongsToCardTx {
	return &cardTagBelongsToCardTx{a.db.Model(m).Association(a.Name())}
}

func (a cardTagBelongsToCard) Unscoped() *cardTagBelongsToCard {
	a.db = a.db.Unscoped()
	return &a
}

type cardTagBelongsToCardTx struct{ tx *gorm.Association }

func (a cardTagBelongsToCardTx) Find() (result *models.Card, err error) {
	return result, a.tx.Find(&result)
}

func (a cardTagBelongsToCardTx) Append(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a cardTagBelongsToCardTx) Replace(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a cardTagBelongsToCardTx) Delete(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a cardTagBelongsToCardTx) Clear() error {
	return a.tx.Clear()
}

func (a cardTagBelongsToCardTx) Count() int64 {
	return a.tx.Count()
}

func (a cardTagBelongsToCardTx) Unscoped() *cardTagBelongsToCardTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type cardTagBelongsToTag struct {
	db *gorm.DB

	field.RelationField
}

func (a cardTagBelongsToTag) Where(conds ...field.Expr) *cardTagBelongsToTag {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a cardTagBelongsToTag) WithContext(ctx context.Context) *cardTagBelongsToTag {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a cardTagBelongsToTag) Session(session *gorm.Session) *cardTagBelongsToTag {
	a.db = a.db.Session(session)
	return &a
}

func (a cardTagBelongsToTag) Model(m *models.CardTag) *cardTagBelongsToTagTx {
	return &cardTagBelongsToTagTx{a.db.Model(m).Association(a.Name())}
}

func (a cardTagBelongsToTag) Unscoped() *cardTagBelongsToTag {
	a.db = a.db.Unscoped()
	return &a
}

type cardTagBelongsToTagTx struct{ tx *gorm.Association }

func (a cardTagBelongsToTagTx) Find() (result *models.Tag, err error) {
	return result, a.tx.Find(&result)
}

func (a cardTagBelongsToTagTx) Append(values ...*models.Tag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a cardTagBelongsToTagTx) Replace(values ...*models.Tag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a cardTagBelongsToTagTx) Delete(values ...*models.Tag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a cardTagBelongsToTagTx) Clear() error {
	return a.tx.Clear()
}

func (a cardTagBelongsToTagTx) Count() int64 {
	return a.tx.Count()
}

func (a cardTagBelongsToTagTx) Unscoped() *cardTagBelongsToTagTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type cardTagDo struct{ gen.DO }

type ICardTagDo interface {
	gen.SubQuery
	Debug() ICardTagDo
	WithContext(ctx context.Context) ICardTagDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICardTagDo
	WriteDB() ICardTagDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICardTagDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICardTagDo
	Not(conds ...gen.Condition) ICardTagDo
	Or(conds ...gen.Condition) ICardTagDo
	Select(conds ...field.Expr) ICardTagDo
	Where(conds ...gen.Condition) ICardTagDo
	Order(conds ...field.Expr) ICardTagDo
	Distinct(cols ...field.Expr) ICardTagDo
	Omit(cols ...field.Expr) ICardTagDo
	Join(table schema.Tabler, on ...field.Expr) ICardTagDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICardTagDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICardTagDo
	Group(cols ...field.Expr) ICardTagDo
	Having(conds ...gen.Condition) ICardTagDo
	Limit(limit int) ICardTagDo
	Offset(offset int) ICardTagDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICardTagDo
	Unscoped() ICardTagDo
	Create(values ...*models.CardTag) error
	CreateInBatches(values []*models.CardTag, batchSize int) error
	Save(values ...*models.CardTag) error
	First() (*models.CardTag, error)
	Take() (*models.CardTag, error)
	Last() (*models.CardTag, error)
	Find() ([]*models.CardTag, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CardTag, err error)
	FindInBatches(result *[]*models.CardTag, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.CardTag) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICardTagDo
	Assign(attrs ...field.AssignExpr) ICardTagDo
	Joins(fields ...field.RelationField) ICardTagDo
	Preload(fields ...field.RelationField) ICardTagDo
	FirstOrInit() (*models.CardTag, error)
	FirstOrCreate() (*models.CardTag, error)
	FindByPage(offset int, limit int) (result []*models.CardTag, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICardTagDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cardTagDo) Debug() ICardTagDo {
	return c.withDO(c.DO.Debug())
}

func (c cardTagDo) WithContext(ctx context.Context) ICardTagDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cardTagDo) ReadDB() ICardTagDo {
	return c.Clauses(dbresolver.Read)
}

func (c cardTagDo) WriteDB() ICardTagDo {
	return c.Clauses(dbresolver.Write)
}

func (c cardTagDo) Session(config *gorm.Session) ICardTagDo {
	return c.withDO(c.DO.Session(config))
}

func (c cardTagDo) Clauses(conds ...clause.Expression) ICardTagDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cardTagDo) Returning(value interface{}, columns ...string) ICardTagDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cardTagDo) Not(conds ...gen.Condition) ICardTagDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cardTagDo) Or(conds ...gen.Condition) ICardTagDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cardTagDo) Select(conds ...field.Expr) ICardTagDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cardTagDo) Where(conds ...gen.Condition) ICardTagDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cardTagDo) Order(conds ...field.Expr) ICardTagDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cardTagDo) Distinct(cols ...field.Expr) ICardTagDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cardTagDo) Omit(cols ...field.Expr) ICardTagDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cardTagDo) Join(table schema.Tabler, on ...field.Expr) ICardTagDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cardTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICardTagDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cardTagDo) RightJoin(table schema.Tabler, on ...field.Expr) ICardTagDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cardTagDo) Group(cols ...field.Expr) ICardTagDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cardTagDo) Having(conds ...gen.Condition) ICardTagDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cardTagDo) Limit(limit int) ICardTagDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cardTagDo) Offset(offset int) ICardTagDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cardTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICardTagDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cardTagDo) Unscoped() ICardTagDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cardTagDo) Create(values ...*models.CardTag) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cardTagDo) CreateInBatches(values []*models.CardTag, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cardTagDo) Save(values ...*models.CardTag) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cardTagDo) First() (*models.CardTag, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.CardTag), nil
	}
}

func (c cardTagDo) Take() (*models.CardTag, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.CardTag), nil
	}
}

func (c cardTagDo) Last() (*models.CardTag, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.CardTag), nil
	}
}

func (c cardTagDo) Find() ([]*models.CardTag, error) {
	result, err := c.DO.Find()
	return result.([]*models.CardTag), err
}

func (c cardTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CardTag, err error) {
	buf := make([]*models.CardTag, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cardTagDo) FindInBatches(result *[]*models.CardTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cardTagDo) Attrs(attrs ...field.AssignExpr) ICardTagDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cardTagDo) Assign(attrs ...field.AssignExpr) ICardTagDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cardTagDo) Joins(fields ...field.RelationField) ICardTagDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cardTagDo) Preload(fields ...field.RelationField) ICardTagDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cardTagDo) FirstOrInit() (*models.CardTag, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.CardTag), nil
	}
}

func (c cardTagDo) FirstOrCreate() (*models.CardTag, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.CardTag), nil
	}
}

func (c cardTagDo) FindByPage(offset int, limit int) (result []*models.CardTag, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cardTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cardTagDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cardTagDo) Delete(models ...*models.CardTag) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cardTagDo) withDO(do gen.Dao) *cardTagDo {
	c.DO = *do.(*gen.DO)
	return c
}
