// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kmemo/internal/storage/models"
)

func newFSRSParameter(db *gorm.DB, opts ...gen.DOOption) fSRSParameter {
	_fSRSParameter := fSRSParameter{}

	_fSRSParameter.fSRSParameterDo.UseDB(db, opts...)
	_fSRSParameter.fSRSParameterDo.UseModel(&models.FSRSParameter{})

	tableName := _fSRSParameter.fSRSParameterDo.TableName()
	_fSRSParameter.ALL = field.NewAsterisk(tableName)
	_fSRSParameter.ID = field.NewString(tableName, "id")
	_fSRSParameter.Name = field.NewString(tableName, "name")
	_fSRSParameter.ParametersJSON = field.NewString(tableName, "parameters_json")
	_fSRSParameter.DesiredRetention = field.NewFloat64(tableName, "desired_retention")
	_fSRSParameter.MaximumInterval = field.NewInt(tableName, "maximum_interval")
	_fSRSParameter.CreatedAt = field.NewTime(tableName, "created_at")
	_fSRSParameter.UpdatedAt = field.NewTime(tableName, "updated_at")

	_fSRSParameter.fillFieldMap()

	return _fSRSParameter
}

type fSRSParameter struct {
	fSRSParameterDo fSRSParameterDo

	ALL              field.Asterisk
	ID               field.String
	Name             field.String
	ParametersJSON   field.String
	DesiredRetention field.Float64
	MaximumInterval  field.Int
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (f fSRSParameter) Table(newTableName string) *fSRSParameter {
	f.fSRSParameterDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fSRSParameter) As(alias string) *fSRSParameter {
	f.fSRSParameterDo.DO = *(f.fSRSParameterDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fSRSParameter) updateTableName(table string) *fSRSParameter {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewString(table, "id")
	f.Name = field.NewString(table, "name")
	f.ParametersJSON = field.NewString(table, "parameters_json")
	f.DesiredRetention = field.NewFloat64(table, "desired_retention")
	f.MaximumInterval = field.NewInt(table, "maximum_interval")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *fSRSParameter) WithContext(ctx context.Context) IFSRSParameterDo {
	return f.fSRSParameterDo.WithContext(ctx)
}

func (f fSRSParameter) TableName() string { return f.fSRSParameterDo.TableName() }

func (f fSRSParameter) Alias() string { return f.fSRSParameterDo.Alias() }

func (f fSRSParameter) Columns(cols ...field.Expr) gen.Columns {
	return f.fSRSParameterDo.Columns(cols...)
}

func (f *fSRSParameter) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fSRSParameter) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 7)
	f.fieldMap["id"] = f.ID
	f.fieldMap["name"] = f.Name
	f.fieldMap["parameters_json"] = f.ParametersJSON
	f.fieldMap["desired_retention"] = f.DesiredRetention
	f.fieldMap["maximum_interval"] = f.MaximumInterval
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f fSRSParameter) clone(db *gorm.DB) fSRSParameter {
	f.fSRSParameterDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fSRSParameter) replaceDB(db *gorm.DB) fSRSParameter {
	f.fSRSParameterDo.ReplaceDB(db)
	return f
}

type fSRSParameterDo struct{ gen.DO }

type IFSRSParameterDo interface {
	gen.SubQuery
	Debug() IFSRSParameterDo
	WithContext(ctx context.Context) IFSRSParameterDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFSRSParameterDo
	WriteDB() IFSRSParameterDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFSRSParameterDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFSRSParameterDo
	Not(conds ...gen.Condition) IFSRSParameterDo
	Or(conds ...gen.Condition) IFSRSParameterDo
	Select(conds ...field.Expr) IFSRSParameterDo
	Where(conds ...gen.Condition) IFSRSParameterDo
	Order(conds ...field.Expr) IFSRSParameterDo
	Distinct(cols ...field.Expr) IFSRSParameterDo
	Omit(cols ...field.Expr) IFSRSParameterDo
	Join(table schema.Tabler, on ...field.Expr) IFSRSParameterDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFSRSParameterDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFSRSParameterDo
	Group(cols ...field.Expr) IFSRSParameterDo
	Having(conds ...gen.Condition) IFSRSParameterDo
	Limit(limit int) IFSRSParameterDo
	Offset(offset int) IFSRSParameterDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFSRSParameterDo
	Unscoped() IFSRSParameterDo
	Create(values ...*models.FSRSParameter) error
	CreateInBatches(values []*models.FSRSParameter, batchSize int) error
	Save(values ...*models.FSRSParameter) error
	First() (*models.FSRSParameter, error)
	Take() (*models.FSRSParameter, error)
	Last() (*models.FSRSParameter, error)
	Find() ([]*models.FSRSParameter, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.FSRSParameter, err error)
	FindInBatches(result *[]*models.FSRSParameter, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.FSRSParameter) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFSRSParameterDo
	Assign(attrs ...field.AssignExpr) IFSRSParameterDo
	Joins(fields ...field.RelationField) IFSRSParameterDo
	Preload(fields ...field.RelationField) IFSRSParameterDo
	FirstOrInit() (*models.FSRSParameter, error)
	FirstOrCreate() (*models.FSRSParameter, error)
	FindByPage(offset int, limit int) (result []*models.FSRSParameter, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFSRSParameterDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f fSRSParameterDo) Debug() IFSRSParameterDo {
	return f.withDO(f.DO.Debug())
}

func (f fSRSParameterDo) WithContext(ctx context.Context) IFSRSParameterDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fSRSParameterDo) ReadDB() IFSRSParameterDo {
	return f.Clauses(dbresolver.Read)
}

func (f fSRSParameterDo) WriteDB() IFSRSParameterDo {
	return f.Clauses(dbresolver.Write)
}

func (f fSRSParameterDo) Session(config *gorm.Session) IFSRSParameterDo {
	return f.withDO(f.DO.Session(config))
}

func (f fSRSParameterDo) Clauses(conds ...clause.Expression) IFSRSParameterDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fSRSParameterDo) Returning(value interface{}, columns ...string) IFSRSParameterDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fSRSParameterDo) Not(conds ...gen.Condition) IFSRSParameterDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fSRSParameterDo) Or(conds ...gen.Condition) IFSRSParameterDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fSRSParameterDo) Select(conds ...field.Expr) IFSRSParameterDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fSRSParameterDo) Where(conds ...gen.Condition) IFSRSParameterDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fSRSParameterDo) Order(conds ...field.Expr) IFSRSParameterDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fSRSParameterDo) Distinct(cols ...field.Expr) IFSRSParameterDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fSRSParameterDo) Omit(cols ...field.Expr) IFSRSParameterDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fSRSParameterDo) Join(table schema.Tabler, on ...field.Expr) IFSRSParameterDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fSRSParameterDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFSRSParameterDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fSRSParameterDo) RightJoin(table schema.Tabler, on ...field.Expr) IFSRSParameterDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fSRSParameterDo) Group(cols ...field.Expr) IFSRSParameterDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fSRSParameterDo) Having(conds ...gen.Condition) IFSRSParameterDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fSRSParameterDo) Limit(limit int) IFSRSParameterDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fSRSParameterDo) Offset(offset int) IFSRSParameterDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fSRSParameterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFSRSParameterDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fSRSParameterDo) Unscoped() IFSRSParameterDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fSRSParameterDo) Create(values ...*models.FSRSParameter) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fSRSParameterDo) CreateInBatches(values []*models.FSRSParameter, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fSRSParameterDo) Save(values ...*models.FSRSParameter) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fSRSParameterDo) First() (*models.FSRSParameter, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.FSRSParameter), nil
	}
}

func (f fSRSParameterDo) Take() (*models.FSRSParameter, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.FSRSParameter), nil
	}
}

func (f fSRSParameterDo) Last() (*models.FSRSParameter, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.FSRSParameter), nil
	}
}

func (f fSRSParameterDo) Find() ([]*models.FSRSParameter, error) {
	result, err := f.DO.Find()
	return result.([]*models.FSRSParameter), err
}

func (f fSRSParameterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.FSRSParameter, err error) {
	buf := make([]*models.FSRSParameter, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fSRSParameterDo) FindInBatches(result *[]*models.FSRSParameter, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fSRSParameterDo) Attrs(attrs ...field.AssignExpr) IFSRSParameterDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fSRSParameterDo) Assign(attrs ...field.AssignExpr) IFSRSParameterDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fSRSParameterDo) Joins(fields ...field.RelationField) IFSRSParameterDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fSRSParameterDo) Preload(fields ...field.RelationField) IFSRSParameterDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fSRSParameterDo) FirstOrInit() (*models.FSRSParameter, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.FSRSParameter), nil
	}
}

func (f fSRSParameterDo) FirstOrCreate() (*models.FSRSParameter, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.FSRSParameter), nil
	}
}

func (f fSRSParameterDo) FindByPage(offset int, limit int) (result []*models.FSRSParameter, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fSRSParameterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fSRSParameterDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fSRSParameterDo) Delete(models ...*models.FSRSParameter) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fSRSParameterDo) withDO(do gen.Dao) *fSRSParameterDo {
	f.DO = *do.(*gen.DO)
	return f
}
