// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	Asset            *asset
	Card             *card
	CardSRS          *cardSRS
	CardTag          *cardTag
	FSRSParameter    *fSRSParameter
	Knowledge        *knowledge
	ReviewLog        *reviewLog
	SearchIndexState *searchIndexState
	SourceDocument   *sourceDocument
	Tag              *tag
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Asset = &Q.Asset
	Card = &Q.Card
	CardSRS = &Q.CardSRS
	CardTag = &Q.CardTag
	FSRSParameter = &Q.FSRSParameter
	Knowledge = &Q.Knowledge
	ReviewLog = &Q.ReviewLog
	SearchIndexState = &Q.SearchIndexState
	SourceDocument = &Q.SourceDocument
	Tag = &Q.Tag
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		Asset:            newAsset(db, opts...),
		Card:             newCard(db, opts...),
		CardSRS:          newCardSRS(db, opts...),
		CardTag:          newCardTag(db, opts...),
		FSRSParameter:    newFSRSParameter(db, opts...),
		Knowledge:        newKnowledge(db, opts...),
		ReviewLog:        newReviewLog(db, opts...),
		SearchIndexState: newSearchIndexState(db, opts...),
		SourceDocument:   newSourceDocument(db, opts...),
		Tag:              newTag(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Asset            asset
	Card             card
	CardSRS          cardSRS
	CardTag          cardTag
	FSRSParameter    fSRSParameter
	Knowledge        knowledge
	ReviewLog        reviewLog
	SearchIndexState searchIndexState
	SourceDocument   sourceDocument
	Tag              tag
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Asset:            q.Asset.clone(db),
		Card:             q.Card.clone(db),
		CardSRS:          q.CardSRS.clone(db),
		CardTag:          q.CardTag.clone(db),
		FSRSParameter:    q.FSRSParameter.clone(db),
		Knowledge:        q.Knowledge.clone(db),
		ReviewLog:        q.ReviewLog.clone(db),
		SearchIndexState: q.SearchIndexState.clone(db),
		SourceDocument:   q.SourceDocument.clone(db),
		Tag:              q.Tag.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Asset:            q.Asset.replaceDB(db),
		Card:             q.Card.replaceDB(db),
		CardSRS:          q.CardSRS.replaceDB(db),
		CardTag:          q.CardTag.replaceDB(db),
		FSRSParameter:    q.FSRSParameter.replaceDB(db),
		Knowledge:        q.Knowledge.replaceDB(db),
		ReviewLog:        q.ReviewLog.replaceDB(db),
		SearchIndexState: q.SearchIndexState.replaceDB(db),
		SourceDocument:   q.SourceDocument.replaceDB(db),
		Tag:              q.Tag.replaceDB(db),
	}
}

type queryCtx struct {
	Asset            IAssetDo
	Card             ICardDo
	CardSRS          ICardSRSDo
	CardTag          ICardTagDo
	FSRSParameter    IFSRSParameterDo
	Knowledge        IKnowledgeDo
	ReviewLog        IReviewLogDo
	SearchIndexState ISearchIndexStateDo
	SourceDocument   ISourceDocumentDo
	Tag              ITagDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Asset:            q.Asset.WithContext(ctx),
		Card:             q.Card.WithContext(ctx),
		CardSRS:          q.CardSRS.WithContext(ctx),
		CardTag:          q.CardTag.WithContext(ctx),
		FSRSParameter:    q.FSRSParameter.WithContext(ctx),
		Knowledge:        q.Knowledge.WithContext(ctx),
		ReviewLog:        q.ReviewLog.WithContext(ctx),
		SearchIndexState: q.SearchIndexState.WithContext(ctx),
		SourceDocument:   q.SourceDocument.WithContext(ctx),
		Tag:              q.Tag.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
