// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kmemo/internal/storage/models"
)

func newKnowledge(db *gorm.DB, opts ...gen.DOOption) knowledge {
	_knowledge := knowledge{}

	_knowledge.knowledgeDo.UseDB(db, opts...)
	_knowledge.knowledgeDo.UseModel(&models.Knowledge{})

	tableName := _knowledge.knowledgeDo.TableName()
	_knowledge.ALL = field.NewAsterisk(tableName)
	_knowledge.ID = field.NewString(tableName, "id")
	_knowledge.Name = field.NewString(tableName, "name")
	_knowledge.Description = field.NewString(tableName, "description")
	_knowledge.ParentID = field.NewString(tableName, "parent_id")
	_knowledge.FSRSPresetID = field.NewString(tableName, "fsrs_preset_id")
	_knowledge.CreatedAt = field.NewTime(tableName, "created_at")
	_knowledge.UpdatedAt = field.NewTime(tableName, "updated_at")
	_knowledge.ArchivedAt = field.NewTime(tableName, "archived_at")
	_knowledge.Children = knowledgeHasManyChildren{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Children", "models.Knowledge"),
		Parent: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Children.Parent", "models.Knowledge"),
		},
		FSRSPreset: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Children.FSRSPreset", "models.FSRSParameter"),
		},
		Children: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Children.Children", "models.Knowledge"),
		},
		SourceDocuments: struct {
			field.RelationField
			Knowledge struct {
				field.RelationField
			}
			Cards struct {
				field.RelationField
				Knowledge struct {
					field.RelationField
				}
				SourceDocument struct {
					field.RelationField
				}
				Parent struct {
					field.RelationField
				}
				CoverAsset struct {
					field.RelationField
					Card struct {
						field.RelationField
					}
				}
				SRS struct {
					field.RelationField
					Card struct {
						field.RelationField
					}
				}
				Children struct {
					field.RelationField
				}
				Assets struct {
					field.RelationField
				}
				CardTags struct {
					field.RelationField
					Card struct {
						field.RelationField
					}
					Tag struct {
						field.RelationField
						CardTags struct {
							field.RelationField
						}
					}
				}
			}
		}{
			RelationField: field.NewRelation("Children.SourceDocuments", "models.SourceDocument"),
			Knowledge: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Children.SourceDocuments.Knowledge", "models.Knowledge"),
			},
			Cards: struct {
				field.RelationField
				Knowledge struct {
					field.RelationField
				}
				SourceDocument struct {
					field.RelationField
				}
				Parent struct {
					field.RelationField
				}
				CoverAsset struct {
					field.RelationField
					Card struct {
						field.RelationField
					}
				}
				SRS struct {
					field.RelationField
					Card struct {
						field.RelationField
					}
				}
				Children struct {
					field.RelationField
				}
				Assets struct {
					field.RelationField
				}
				CardTags struct {
					field.RelationField
					Card struct {
						field.RelationField
					}
					Tag struct {
						field.RelationField
						CardTags struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("Children.SourceDocuments.Cards", "models.Card"),
				Knowledge: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Children.SourceDocuments.Cards.Knowledge", "models.Knowledge"),
				},
				SourceDocument: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Children.SourceDocuments.Cards.SourceDocument", "models.SourceDocument"),
				},
				Parent: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Children.SourceDocuments.Cards.Parent", "models.Card"),
				},
				CoverAsset: struct {
					field.RelationField
					Card struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Children.SourceDocuments.Cards.CoverAsset", "models.Asset"),
					Card: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Children.SourceDocuments.Cards.CoverAsset.Card", "models.Card"),
					},
				},
				SRS: struct {
					field.RelationField
					Card struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Children.SourceDocuments.Cards.SRS", "models.CardSRS"),
					Card: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Children.SourceDocuments.Cards.SRS.Card", "models.Card"),
					},
				},
				Children: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Children.SourceDocuments.Cards.Children", "models.Card"),
				},
				Assets: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Children.SourceDocuments.Cards.Assets", "models.Asset"),
				},
				CardTags: struct {
					field.RelationField
					Card struct {
						field.RelationField
					}
					Tag struct {
						field.RelationField
						CardTags struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("Children.SourceDocuments.Cards.CardTags", "models.CardTag"),
					Card: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Children.SourceDocuments.Cards.CardTags.Card", "models.Card"),
					},
					Tag: struct {
						field.RelationField
						CardTags struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Children.SourceDocuments.Cards.CardTags.Tag", "models.Tag"),
						CardTags: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Children.SourceDocuments.Cards.CardTags.Tag.CardTags", "models.CardTag"),
						},
					},
				},
			},
		},
		Cards: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Children.Cards", "models.Card"),
		},
	}

	_knowledge.SourceDocuments = knowledgeHasManySourceDocuments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SourceDocuments", "models.SourceDocument"),
	}

	_knowledge.Cards = knowledgeHasManyCards{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Cards", "models.Card"),
	}

	_knowledge.Parent = knowledgeBelongsToParent{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Parent", "models.Knowledge"),
	}

	_knowledge.FSRSPreset = knowledgeBelongsToFSRSPreset{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("FSRSPreset", "models.FSRSParameter"),
	}

	_knowledge.fillFieldMap()

	return _knowledge
}

type knowledge struct {
	knowledgeDo knowledgeDo

	ALL          field.Asterisk
	ID           field.String
	Name         field.String
	Description  field.String
	ParentID     field.String
	FSRSPresetID field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time
	ArchivedAt   field.Time
	Children     knowledgeHasManyChildren

	SourceDocuments knowledgeHasManySourceDocuments

	Cards knowledgeHasManyCards

	Parent knowledgeBelongsToParent

	FSRSPreset knowledgeBelongsToFSRSPreset

	fieldMap map[string]field.Expr
}

func (k knowledge) Table(newTableName string) *knowledge {
	k.knowledgeDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k knowledge) As(alias string) *knowledge {
	k.knowledgeDo.DO = *(k.knowledgeDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *knowledge) updateTableName(table string) *knowledge {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewString(table, "id")
	k.Name = field.NewString(table, "name")
	k.Description = field.NewString(table, "description")
	k.ParentID = field.NewString(table, "parent_id")
	k.FSRSPresetID = field.NewString(table, "fsrs_preset_id")
	k.CreatedAt = field.NewTime(table, "created_at")
	k.UpdatedAt = field.NewTime(table, "updated_at")
	k.ArchivedAt = field.NewTime(table, "archived_at")

	k.fillFieldMap()

	return k
}

func (k *knowledge) WithContext(ctx context.Context) IKnowledgeDo {
	return k.knowledgeDo.WithContext(ctx)
}

func (k knowledge) TableName() string { return k.knowledgeDo.TableName() }

func (k knowledge) Alias() string { return k.knowledgeDo.Alias() }

func (k knowledge) Columns(cols ...field.Expr) gen.Columns { return k.knowledgeDo.Columns(cols...) }

func (k *knowledge) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *knowledge) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 13)
	k.fieldMap["id"] = k.ID
	k.fieldMap["name"] = k.Name
	k.fieldMap["description"] = k.Description
	k.fieldMap["parent_id"] = k.ParentID
	k.fieldMap["fsrs_preset_id"] = k.FSRSPresetID
	k.fieldMap["created_at"] = k.CreatedAt
	k.fieldMap["updated_at"] = k.UpdatedAt
	k.fieldMap["archived_at"] = k.ArchivedAt

}

func (k knowledge) clone(db *gorm.DB) knowledge {
	k.knowledgeDo.ReplaceConnPool(db.Statement.ConnPool)
	k.Children.db = db.Session(&gorm.Session{Initialized: true})
	k.Children.db.Statement.ConnPool = db.Statement.ConnPool
	k.SourceDocuments.db = db.Session(&gorm.Session{Initialized: true})
	k.SourceDocuments.db.Statement.ConnPool = db.Statement.ConnPool
	k.Cards.db = db.Session(&gorm.Session{Initialized: true})
	k.Cards.db.Statement.ConnPool = db.Statement.ConnPool
	k.Parent.db = db.Session(&gorm.Session{Initialized: true})
	k.Parent.db.Statement.ConnPool = db.Statement.ConnPool
	k.FSRSPreset.db = db.Session(&gorm.Session{Initialized: true})
	k.FSRSPreset.db.Statement.ConnPool = db.Statement.ConnPool
	return k
}

func (k knowledge) replaceDB(db *gorm.DB) knowledge {
	k.knowledgeDo.ReplaceDB(db)
	k.Children.db = db.Session(&gorm.Session{})
	k.SourceDocuments.db = db.Session(&gorm.Session{})
	k.Cards.db = db.Session(&gorm.Session{})
	k.Parent.db = db.Session(&gorm.Session{})
	k.FSRSPreset.db = db.Session(&gorm.Session{})
	return k
}

type knowledgeHasManyChildren struct {
	db *gorm.DB

	field.RelationField

	Parent struct {
		field.RelationField
	}
	FSRSPreset struct {
		field.RelationField
	}
	Children struct {
		field.RelationField
	}
	SourceDocuments struct {
		field.RelationField
		Knowledge struct {
			field.RelationField
		}
		Cards struct {
			field.RelationField
			Knowledge struct {
				field.RelationField
			}
			SourceDocument struct {
				field.RelationField
			}
			Parent struct {
				field.RelationField
			}
			CoverAsset struct {
				field.RelationField
				Card struct {
					field.RelationField
				}
			}
			SRS struct {
				field.RelationField
				Card struct {
					field.RelationField
				}
			}
			Children struct {
				field.RelationField
			}
			Assets struct {
				field.RelationField
			}
			CardTags struct {
				field.RelationField
				Card struct {
					field.RelationField
				}
				Tag struct {
					field.RelationField
					CardTags struct {
						field.RelationField
					}
				}
			}
		}
	}
	Cards struct {
		field.RelationField
	}
}

func (a knowledgeHasManyChildren) Where(conds ...field.Expr) *knowledgeHasManyChildren {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a knowledgeHasManyChildren) WithContext(ctx context.Context) *knowledgeHasManyChildren {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a knowledgeHasManyChildren) Session(session *gorm.Session) *knowledgeHasManyChildren {
	a.db = a.db.Session(session)
	return &a
}

func (a knowledgeHasManyChildren) Model(m *models.Knowledge) *knowledgeHasManyChildrenTx {
	return &knowledgeHasManyChildrenTx{a.db.Model(m).Association(a.Name())}
}

func (a knowledgeHasManyChildren) Unscoped() *knowledgeHasManyChildren {
	a.db = a.db.Unscoped()
	return &a
}

type knowledgeHasManyChildrenTx struct{ tx *gorm.Association }

func (a knowledgeHasManyChildrenTx) Find() (result []*models.Knowledge, err error) {
	return result, a.tx.Find(&result)
}

func (a knowledgeHasManyChildrenTx) Append(values ...*models.Knowledge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a knowledgeHasManyChildrenTx) Replace(values ...*models.Knowledge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a knowledgeHasManyChildrenTx) Delete(values ...*models.Knowledge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a knowledgeHasManyChildrenTx) Clear() error {
	return a.tx.Clear()
}

func (a knowledgeHasManyChildrenTx) Count() int64 {
	return a.tx.Count()
}

func (a knowledgeHasManyChildrenTx) Unscoped() *knowledgeHasManyChildrenTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type knowledgeHasManySourceDocuments struct {
	db *gorm.DB

	field.RelationField
}

func (a knowledgeHasManySourceDocuments) Where(conds ...field.Expr) *knowledgeHasManySourceDocuments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a knowledgeHasManySourceDocuments) WithContext(ctx context.Context) *knowledgeHasManySourceDocuments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a knowledgeHasManySourceDocuments) Session(session *gorm.Session) *knowledgeHasManySourceDocuments {
	a.db = a.db.Session(session)
	return &a
}

func (a knowledgeHasManySourceDocuments) Model(m *models.Knowledge) *knowledgeHasManySourceDocumentsTx {
	return &knowledgeHasManySourceDocumentsTx{a.db.Model(m).Association(a.Name())}
}

func (a knowledgeHasManySourceDocuments) Unscoped() *knowledgeHasManySourceDocuments {
	a.db = a.db.Unscoped()
	return &a
}

type knowledgeHasManySourceDocumentsTx struct{ tx *gorm.Association }

func (a knowledgeHasManySourceDocumentsTx) Find() (result []*models.SourceDocument, err error) {
	return result, a.tx.Find(&result)
}

func (a knowledgeHasManySourceDocumentsTx) Append(values ...*models.SourceDocument) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a knowledgeHasManySourceDocumentsTx) Replace(values ...*models.SourceDocument) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a knowledgeHasManySourceDocumentsTx) Delete(values ...*models.SourceDocument) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a knowledgeHasManySourceDocumentsTx) Clear() error {
	return a.tx.Clear()
}

func (a knowledgeHasManySourceDocumentsTx) Count() int64 {
	return a.tx.Count()
}

func (a knowledgeHasManySourceDocumentsTx) Unscoped() *knowledgeHasManySourceDocumentsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type knowledgeHasManyCards struct {
	db *gorm.DB

	field.RelationField
}

func (a knowledgeHasManyCards) Where(conds ...field.Expr) *knowledgeHasManyCards {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a knowledgeHasManyCards) WithContext(ctx context.Context) *knowledgeHasManyCards {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a knowledgeHasManyCards) Session(session *gorm.Session) *knowledgeHasManyCards {
	a.db = a.db.Session(session)
	return &a
}

func (a knowledgeHasManyCards) Model(m *models.Knowledge) *knowledgeHasManyCardsTx {
	return &knowledgeHasManyCardsTx{a.db.Model(m).Association(a.Name())}
}

func (a knowledgeHasManyCards) Unscoped() *knowledgeHasManyCards {
	a.db = a.db.Unscoped()
	return &a
}

type knowledgeHasManyCardsTx struct{ tx *gorm.Association }

func (a knowledgeHasManyCardsTx) Find() (result []*models.Card, err error) {
	return result, a.tx.Find(&result)
}

func (a knowledgeHasManyCardsTx) Append(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a knowledgeHasManyCardsTx) Replace(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a knowledgeHasManyCardsTx) Delete(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a knowledgeHasManyCardsTx) Clear() error {
	return a.tx.Clear()
}

func (a knowledgeHasManyCardsTx) Count() int64 {
	return a.tx.Count()
}

func (a knowledgeHasManyCardsTx) Unscoped() *knowledgeHasManyCardsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type knowledgeBelongsToParent struct {
	db *gorm.DB

	field.RelationField
}

func (a knowledgeBelongsToParent) Where(conds ...field.Expr) *knowledgeBelongsToParent {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a knowledgeBelongsToParent) WithContext(ctx context.Context) *knowledgeBelongsToParent {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a knowledgeBelongsToParent) Session(session *gorm.Session) *knowledgeBelongsToParent {
	a.db = a.db.Session(session)
	return &a
}

func (a knowledgeBelongsToParent) Model(m *models.Knowledge) *knowledgeBelongsToParentTx {
	return &knowledgeBelongsToParentTx{a.db.Model(m).Association(a.Name())}
}

func (a knowledgeBelongsToParent) Unscoped() *knowledgeBelongsToParent {
	a.db = a.db.Unscoped()
	return &a
}

type knowledgeBelongsToParentTx struct{ tx *gorm.Association }

func (a knowledgeBelongsToParentTx) Find() (result *models.Knowledge, err error) {
	return result, a.tx.Find(&result)
}

func (a knowledgeBelongsToParentTx) Append(values ...*models.Knowledge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a knowledgeBelongsToParentTx) Replace(values ...*models.Knowledge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a knowledgeBelongsToParentTx) Delete(values ...*models.Knowledge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a knowledgeBelongsToParentTx) Clear() error {
	return a.tx.Clear()
}

func (a knowledgeBelongsToParentTx) Count() int64 {
	return a.tx.Count()
}

func (a knowledgeBelongsToParentTx) Unscoped() *knowledgeBelongsToParentTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type knowledgeBelongsToFSRSPreset struct {
	db *gorm.DB

	field.RelationField
}

func (a knowledgeBelongsToFSRSPreset) Where(conds ...field.Expr) *knowledgeBelongsToFSRSPreset {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a knowledgeBelongsToFSRSPreset) WithContext(ctx context.Context) *knowledgeBelongsToFSRSPreset {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a knowledgeBelongsToFSRSPreset) Session(session *gorm.Session) *knowledgeBelongsToFSRSPreset {
	a.db = a.db.Session(session)
	return &a
}

func (a knowledgeBelongsToFSRSPreset) Model(m *models.Knowledge) *knowledgeBelongsToFSRSPresetTx {
	return &knowledgeBelongsToFSRSPresetTx{a.db.Model(m).Association(a.Name())}
}

func (a knowledgeBelongsToFSRSPreset) Unscoped() *knowledgeBelongsToFSRSPreset {
	a.db = a.db.Unscoped()
	return &a
}

type knowledgeBelongsToFSRSPresetTx struct{ tx *gorm.Association }

func (a knowledgeBelongsToFSRSPresetTx) Find() (result *models.FSRSParameter, err error) {
	return result, a.tx.Find(&result)
}

func (a knowledgeBelongsToFSRSPresetTx) Append(values ...*models.FSRSParameter) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a knowledgeBelongsToFSRSPresetTx) Replace(values ...*models.FSRSParameter) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a knowledgeBelongsToFSRSPresetTx) Delete(values ...*models.FSRSParameter) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a knowledgeBelongsToFSRSPresetTx) Clear() error {
	return a.tx.Clear()
}

func (a knowledgeBelongsToFSRSPresetTx) Count() int64 {
	return a.tx.Count()
}

func (a knowledgeBelongsToFSRSPresetTx) Unscoped() *knowledgeBelongsToFSRSPresetTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type knowledgeDo struct{ gen.DO }

type IKnowledgeDo interface {
	gen.SubQuery
	Debug() IKnowledgeDo
	WithContext(ctx context.Context) IKnowledgeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKnowledgeDo
	WriteDB() IKnowledgeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKnowledgeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKnowledgeDo
	Not(conds ...gen.Condition) IKnowledgeDo
	Or(conds ...gen.Condition) IKnowledgeDo
	Select(conds ...field.Expr) IKnowledgeDo
	Where(conds ...gen.Condition) IKnowledgeDo
	Order(conds ...field.Expr) IKnowledgeDo
	Distinct(cols ...field.Expr) IKnowledgeDo
	Omit(cols ...field.Expr) IKnowledgeDo
	Join(table schema.Tabler, on ...field.Expr) IKnowledgeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKnowledgeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKnowledgeDo
	Group(cols ...field.Expr) IKnowledgeDo
	Having(conds ...gen.Condition) IKnowledgeDo
	Limit(limit int) IKnowledgeDo
	Offset(offset int) IKnowledgeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKnowledgeDo
	Unscoped() IKnowledgeDo
	Create(values ...*models.Knowledge) error
	CreateInBatches(values []*models.Knowledge, batchSize int) error
	Save(values ...*models.Knowledge) error
	First() (*models.Knowledge, error)
	Take() (*models.Knowledge, error)
	Last() (*models.Knowledge, error)
	Find() ([]*models.Knowledge, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Knowledge, err error)
	FindInBatches(result *[]*models.Knowledge, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Knowledge) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKnowledgeDo
	Assign(attrs ...field.AssignExpr) IKnowledgeDo
	Joins(fields ...field.RelationField) IKnowledgeDo
	Preload(fields ...field.RelationField) IKnowledgeDo
	FirstOrInit() (*models.Knowledge, error)
	FirstOrCreate() (*models.Knowledge, error)
	FindByPage(offset int, limit int) (result []*models.Knowledge, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKnowledgeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k knowledgeDo) Debug() IKnowledgeDo {
	return k.withDO(k.DO.Debug())
}

func (k knowledgeDo) WithContext(ctx context.Context) IKnowledgeDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k knowledgeDo) ReadDB() IKnowledgeDo {
	return k.Clauses(dbresolver.Read)
}

func (k knowledgeDo) WriteDB() IKnowledgeDo {
	return k.Clauses(dbresolver.Write)
}

func (k knowledgeDo) Session(config *gorm.Session) IKnowledgeDo {
	return k.withDO(k.DO.Session(config))
}

func (k knowledgeDo) Clauses(conds ...clause.Expression) IKnowledgeDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k knowledgeDo) Returning(value interface{}, columns ...string) IKnowledgeDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k knowledgeDo) Not(conds ...gen.Condition) IKnowledgeDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k knowledgeDo) Or(conds ...gen.Condition) IKnowledgeDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k knowledgeDo) Select(conds ...field.Expr) IKnowledgeDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k knowledgeDo) Where(conds ...gen.Condition) IKnowledgeDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k knowledgeDo) Order(conds ...field.Expr) IKnowledgeDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k knowledgeDo) Distinct(cols ...field.Expr) IKnowledgeDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k knowledgeDo) Omit(cols ...field.Expr) IKnowledgeDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k knowledgeDo) Join(table schema.Tabler, on ...field.Expr) IKnowledgeDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k knowledgeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKnowledgeDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k knowledgeDo) RightJoin(table schema.Tabler, on ...field.Expr) IKnowledgeDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k knowledgeDo) Group(cols ...field.Expr) IKnowledgeDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k knowledgeDo) Having(conds ...gen.Condition) IKnowledgeDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k knowledgeDo) Limit(limit int) IKnowledgeDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k knowledgeDo) Offset(offset int) IKnowledgeDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k knowledgeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKnowledgeDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k knowledgeDo) Unscoped() IKnowledgeDo {
	return k.withDO(k.DO.Unscoped())
}

func (k knowledgeDo) Create(values ...*models.Knowledge) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k knowledgeDo) CreateInBatches(values []*models.Knowledge, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k knowledgeDo) Save(values ...*models.Knowledge) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k knowledgeDo) First() (*models.Knowledge, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Knowledge), nil
	}
}

func (k knowledgeDo) Take() (*models.Knowledge, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Knowledge), nil
	}
}

func (k knowledgeDo) Last() (*models.Knowledge, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Knowledge), nil
	}
}

func (k knowledgeDo) Find() ([]*models.Knowledge, error) {
	result, err := k.DO.Find()
	return result.([]*models.Knowledge), err
}

func (k knowledgeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Knowledge, err error) {
	buf := make([]*models.Knowledge, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k knowledgeDo) FindInBatches(result *[]*models.Knowledge, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k knowledgeDo) Attrs(attrs ...field.AssignExpr) IKnowledgeDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k knowledgeDo) Assign(attrs ...field.AssignExpr) IKnowledgeDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k knowledgeDo) Joins(fields ...field.RelationField) IKnowledgeDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k knowledgeDo) Preload(fields ...field.RelationField) IKnowledgeDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k knowledgeDo) FirstOrInit() (*models.Knowledge, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Knowledge), nil
	}
}

func (k knowledgeDo) FirstOrCreate() (*models.Knowledge, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Knowledge), nil
	}
}

func (k knowledgeDo) FindByPage(offset int, limit int) (result []*models.Knowledge, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k knowledgeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k knowledgeDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k knowledgeDo) Delete(models ...*models.Knowledge) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *knowledgeDo) withDO(do gen.Dao) *knowledgeDo {
	k.DO = *do.(*gen.DO)
	return k
}
