// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kmemo/internal/storage/models"
)

func newReviewLog(db *gorm.DB, opts ...gen.DOOption) reviewLog {
	_reviewLog := reviewLog{}

	_reviewLog.reviewLogDo.UseDB(db, opts...)
	_reviewLog.reviewLogDo.UseModel(&models.ReviewLog{})

	tableName := _reviewLog.reviewLogDo.TableName()
	_reviewLog.ALL = field.NewAsterisk(tableName)
	_reviewLog.ID = field.NewString(tableName, "id")
	_reviewLog.CardID = field.NewString(tableName, "card_id")
	_reviewLog.ReviewedAt = field.NewTime(tableName, "reviewed_at")
	_reviewLog.Rating = field.NewInt(tableName, "rating")
	_reviewLog.ReviewKind = field.NewString(tableName, "review_kind")
	_reviewLog.ScheduledDays = field.NewFloat64(tableName, "scheduled_days")
	_reviewLog.ElapsedDays = field.NewFloat64(tableName, "elapsed_days")
	_reviewLog.PreviousStability = field.NewFloat64(tableName, "previous_stability")
	_reviewLog.PreviousDifficulty = field.NewFloat64(tableName, "previous_difficulty")
	_reviewLog.NewStability = field.NewFloat64(tableName, "new_stability")
	_reviewLog.NewDifficulty = field.NewFloat64(tableName, "new_difficulty")
	_reviewLog.SnapshotJSON = field.NewString(tableName, "snapshot_json")
	_reviewLog.Card = reviewLogBelongsToCard{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Card", "models.Card"),
		Knowledge: struct {
			field.RelationField
			Parent struct {
				field.RelationField
			}
			FSRSPreset struct {
				field.RelationField
			}
			Children struct {
				field.RelationField
			}
			SourceDocuments struct {
				field.RelationField
				Knowledge struct {
					field.RelationField
				}
				Cards struct {
					field.RelationField
				}
			}
			Cards struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Card.Knowledge", "models.Knowledge"),
			Parent: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.Knowledge.Parent", "models.Knowledge"),
			},
			FSRSPreset: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.Knowledge.FSRSPreset", "models.FSRSParameter"),
			},
			Children: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.Knowledge.Children", "models.Knowledge"),
			},
			SourceDocuments: struct {
				field.RelationField
				Knowledge struct {
					field.RelationField
				}
				Cards struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Card.Knowledge.SourceDocuments", "models.SourceDocument"),
				Knowledge: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Card.Knowledge.SourceDocuments.Knowledge", "models.Knowledge"),
				},
				Cards: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Card.Knowledge.SourceDocuments.Cards", "models.Card"),
				},
			},
			Cards: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.Knowledge.Cards", "models.Card"),
			},
		},
		SourceDocument: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Card.SourceDocument", "models.SourceDocument"),
		},
		Parent: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Card.Parent", "models.Card"),
		},
		CoverAsset: struct {
			field.RelationField
			Card struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Card.CoverAsset", "models.Asset"),
			Card: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.CoverAsset.Card", "models.Card"),
			},
		},
		SRS: struct {
			field.RelationField
			Card struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Card.SRS", "models.CardSRS"),
			Card: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.SRS.Card", "models.Card"),
			},
		},
		Children: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Card.Children", "models.Card"),
		},
		Assets: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Card.Assets", "models.Asset"),
		},
		CardTags: struct {
			field.RelationField
			Card struct {
				field.RelationField
			}
			Tag struct {
				field.RelationField
				CardTags struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Card.CardTags", "models.CardTag"),
			Card: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Card.CardTags.Card", "models.Card"),
			},
			Tag: struct {
				field.RelationField
				CardTags struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Card.CardTags.Tag", "models.Tag"),
				CardTags: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Card.CardTags.Tag.CardTags", "models.CardTag"),
				},
			},
		},
	}

	_reviewLog.fillFieldMap()

	return _reviewLog
}

type reviewLog struct {
	reviewLogDo reviewLogDo

	ALL                field.Asterisk
	ID                 field.String
	CardID             field.String
	ReviewedAt         field.Time
	Rating             field.Int
	ReviewKind         field.String
	ScheduledDays      field.Float64
	ElapsedDays        field.Float64
	PreviousStability  field.Float64
	PreviousDifficulty field.Float64
	NewStability       field.Float64
	NewDifficulty      field.Float64
	SnapshotJSON       field.String
	Card               reviewLogBelongsToCard

	fieldMap map[string]field.Expr
}

func (r reviewLog) Table(newTableName string) *reviewLog {
	r.reviewLogDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r reviewLog) As(alias string) *reviewLog {
	r.reviewLogDo.DO = *(r.reviewLogDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *reviewLog) updateTableName(table string) *reviewLog {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.CardID = field.NewString(table, "card_id")
	r.ReviewedAt = field.NewTime(table, "reviewed_at")
	r.Rating = field.NewInt(table, "rating")
	r.ReviewKind = field.NewString(table, "review_kind")
	r.ScheduledDays = field.NewFloat64(table, "scheduled_days")
	r.ElapsedDays = field.NewFloat64(table, "elapsed_days")
	r.PreviousStability = field.NewFloat64(table, "previous_stability")
	r.PreviousDifficulty = field.NewFloat64(table, "previous_difficulty")
	r.NewStability = field.NewFloat64(table, "new_stability")
	r.NewDifficulty = field.NewFloat64(table, "new_difficulty")
	r.SnapshotJSON = field.NewString(table, "snapshot_json")

	r.fillFieldMap()

	return r
}

func (r *reviewLog) WithContext(ctx context.Context) IReviewLogDo {
	return r.reviewLogDo.WithContext(ctx)
}

func (r reviewLog) TableName() string { return r.reviewLogDo.TableName() }

func (r reviewLog) Alias() string { return r.reviewLogDo.Alias() }

func (r reviewLog) Columns(cols ...field.Expr) gen.Columns { return r.reviewLogDo.Columns(cols...) }

func (r *reviewLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *reviewLog) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 13)
	r.fieldMap["id"] = r.ID
	r.fieldMap["card_id"] = r.CardID
	r.fieldMap["reviewed_at"] = r.ReviewedAt
	r.fieldMap["rating"] = r.Rating
	r.fieldMap["review_kind"] = r.ReviewKind
	r.fieldMap["scheduled_days"] = r.ScheduledDays
	r.fieldMap["elapsed_days"] = r.ElapsedDays
	r.fieldMap["previous_stability"] = r.PreviousStability
	r.fieldMap["previous_difficulty"] = r.PreviousDifficulty
	r.fieldMap["new_stability"] = r.NewStability
	r.fieldMap["new_difficulty"] = r.NewDifficulty
	r.fieldMap["snapshot_json"] = r.SnapshotJSON

}

func (r reviewLog) clone(db *gorm.DB) reviewLog {
	r.reviewLogDo.ReplaceConnPool(db.Statement.ConnPool)
	r.Card.db = db.Session(&gorm.Session{Initialized: true})
	r.Card.db.Statement.ConnPool = db.Statement.ConnPool
	return r
}

func (r reviewLog) replaceDB(db *gorm.DB) reviewLog {
	r.reviewLogDo.ReplaceDB(db)
	r.Card.db = db.Session(&gorm.Session{})
	return r
}

type reviewLogBelongsToCard struct {
	db *gorm.DB

	field.RelationField

	Knowledge struct {
		field.RelationField
		Parent struct {
			field.RelationField
		}
		FSRSPreset struct {
			field.RelationField
		}
		Children struct {
			field.RelationField
		}
		SourceDocuments struct {
			field.RelationField
			Knowledge struct {
				field.RelationField
			}
			Cards struct {
				field.RelationField
			}
		}
		Cards struct {
			field.RelationField
		}
	}
	SourceDocument struct {
		field.RelationField
	}
	Parent struct {
		field.RelationField
	}
	CoverAsset struct {
		field.RelationField
		Card struct {
			field.RelationField
		}
	}
	SRS struct {
		field.RelationField
		Card struct {
			field.RelationField
		}
	}
	Children struct {
		field.RelationField
	}
	Assets struct {
		field.RelationField
	}
	CardTags struct {
		field.RelationField
		Card struct {
			field.RelationField
		}
		Tag struct {
			field.RelationField
			CardTags struct {
				field.RelationField
			}
		}
	}
}

func (a reviewLogBelongsToCard) Where(conds ...field.Expr) *reviewLogBelongsToCard {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a reviewLogBelongsToCard) WithContext(ctx context.Context) *reviewLogBelongsToCard {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a reviewLogBelongsToCard) Session(session *gorm.Session) *reviewLogBelongsToCard {
	a.db = a.db.Session(session)
	return &a
}

func (a reviewLogBelongsToCard) Model(m *models.ReviewLog) *reviewLogBelongsToCardTx {
	return &reviewLogBelongsToCardTx{a.db.Model(m).Association(a.Name())}
}

func (a reviewLogBelongsToCard) Unscoped() *reviewLogBelongsToCard {
	a.db = a.db.Unscoped()
	return &a
}

type reviewLogBelongsToCardTx struct{ tx *gorm.Association }

func (a reviewLogBelongsToCardTx) Find() (result *models.Card, err error) {
	return result, a.tx.Find(&result)
}

func (a reviewLogBelongsToCardTx) Append(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a reviewLogBelongsToCardTx) Replace(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a reviewLogBelongsToCardTx) Delete(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a reviewLogBelongsToCardTx) Clear() error {
	return a.tx.Clear()
}

func (a reviewLogBelongsToCardTx) Count() int64 {
	return a.tx.Count()
}

func (a reviewLogBelongsToCardTx) Unscoped() *reviewLogBelongsToCardTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type reviewLogDo struct{ gen.DO }

type IReviewLogDo interface {
	gen.SubQuery
	Debug() IReviewLogDo
	WithContext(ctx context.Context) IReviewLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IReviewLogDo
	WriteDB() IReviewLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IReviewLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IReviewLogDo
	Not(conds ...gen.Condition) IReviewLogDo
	Or(conds ...gen.Condition) IReviewLogDo
	Select(conds ...field.Expr) IReviewLogDo
	Where(conds ...gen.Condition) IReviewLogDo
	Order(conds ...field.Expr) IReviewLogDo
	Distinct(cols ...field.Expr) IReviewLogDo
	Omit(cols ...field.Expr) IReviewLogDo
	Join(table schema.Tabler, on ...field.Expr) IReviewLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IReviewLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IReviewLogDo
	Group(cols ...field.Expr) IReviewLogDo
	Having(conds ...gen.Condition) IReviewLogDo
	Limit(limit int) IReviewLogDo
	Offset(offset int) IReviewLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IReviewLogDo
	Unscoped() IReviewLogDo
	Create(values ...*models.ReviewLog) error
	CreateInBatches(values []*models.ReviewLog, batchSize int) error
	Save(values ...*models.ReviewLog) error
	First() (*models.ReviewLog, error)
	Take() (*models.ReviewLog, error)
	Last() (*models.ReviewLog, error)
	Find() ([]*models.ReviewLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ReviewLog, err error)
	FindInBatches(result *[]*models.ReviewLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ReviewLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IReviewLogDo
	Assign(attrs ...field.AssignExpr) IReviewLogDo
	Joins(fields ...field.RelationField) IReviewLogDo
	Preload(fields ...field.RelationField) IReviewLogDo
	FirstOrInit() (*models.ReviewLog, error)
	FirstOrCreate() (*models.ReviewLog, error)
	FindByPage(offset int, limit int) (result []*models.ReviewLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IReviewLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r reviewLogDo) Debug() IReviewLogDo {
	return r.withDO(r.DO.Debug())
}

func (r reviewLogDo) WithContext(ctx context.Context) IReviewLogDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r reviewLogDo) ReadDB() IReviewLogDo {
	return r.Clauses(dbresolver.Read)
}

func (r reviewLogDo) WriteDB() IReviewLogDo {
	return r.Clauses(dbresolver.Write)
}

func (r reviewLogDo) Session(config *gorm.Session) IReviewLogDo {
	return r.withDO(r.DO.Session(config))
}

func (r reviewLogDo) Clauses(conds ...clause.Expression) IReviewLogDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r reviewLogDo) Returning(value interface{}, columns ...string) IReviewLogDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r reviewLogDo) Not(conds ...gen.Condition) IReviewLogDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r reviewLogDo) Or(conds ...gen.Condition) IReviewLogDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r reviewLogDo) Select(conds ...field.Expr) IReviewLogDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r reviewLogDo) Where(conds ...gen.Condition) IReviewLogDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r reviewLogDo) Order(conds ...field.Expr) IReviewLogDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r reviewLogDo) Distinct(cols ...field.Expr) IReviewLogDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r reviewLogDo) Omit(cols ...field.Expr) IReviewLogDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r reviewLogDo) Join(table schema.Tabler, on ...field.Expr) IReviewLogDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r reviewLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IReviewLogDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r reviewLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IReviewLogDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r reviewLogDo) Group(cols ...field.Expr) IReviewLogDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r reviewLogDo) Having(conds ...gen.Condition) IReviewLogDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r reviewLogDo) Limit(limit int) IReviewLogDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r reviewLogDo) Offset(offset int) IReviewLogDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r reviewLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IReviewLogDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r reviewLogDo) Unscoped() IReviewLogDo {
	return r.withDO(r.DO.Unscoped())
}

func (r reviewLogDo) Create(values ...*models.ReviewLog) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r reviewLogDo) CreateInBatches(values []*models.ReviewLog, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r reviewLogDo) Save(values ...*models.ReviewLog) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r reviewLogDo) First() (*models.ReviewLog, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ReviewLog), nil
	}
}

func (r reviewLogDo) Take() (*models.ReviewLog, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ReviewLog), nil
	}
}

func (r reviewLogDo) Last() (*models.ReviewLog, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ReviewLog), nil
	}
}

func (r reviewLogDo) Find() ([]*models.ReviewLog, error) {
	result, err := r.DO.Find()
	return result.([]*models.ReviewLog), err
}

func (r reviewLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ReviewLog, err error) {
	buf := make([]*models.ReviewLog, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r reviewLogDo) FindInBatches(result *[]*models.ReviewLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r reviewLogDo) Attrs(attrs ...field.AssignExpr) IReviewLogDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r reviewLogDo) Assign(attrs ...field.AssignExpr) IReviewLogDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r reviewLogDo) Joins(fields ...field.RelationField) IReviewLogDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r reviewLogDo) Preload(fields ...field.RelationField) IReviewLogDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r reviewLogDo) FirstOrInit() (*models.ReviewLog, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ReviewLog), nil
	}
}

func (r reviewLogDo) FirstOrCreate() (*models.ReviewLog, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ReviewLog), nil
	}
}

func (r reviewLogDo) FindByPage(offset int, limit int) (result []*models.ReviewLog, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r reviewLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r reviewLogDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r reviewLogDo) Delete(models ...*models.ReviewLog) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *reviewLogDo) withDO(do gen.Dao) *reviewLogDo {
	r.DO = *do.(*gen.DO)
	return r
}
