// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kmemo/internal/storage/models"
)

func newSearchIndexState(db *gorm.DB, opts ...gen.DOOption) searchIndexState {
	_searchIndexState := searchIndexState{}

	_searchIndexState.searchIndexStateDo.UseDB(db, opts...)
	_searchIndexState.searchIndexStateDo.UseModel(&models.SearchIndexState{})

	tableName := _searchIndexState.searchIndexStateDo.TableName()
	_searchIndexState.ALL = field.NewAsterisk(tableName)
	_searchIndexState.ObjectType = field.NewString(tableName, "object_type")
	_searchIndexState.ObjectID = field.NewString(tableName, "object_id")
	_searchIndexState.ContentHash = field.NewString(tableName, "content_hash")
	_searchIndexState.IndexedHash = field.NewString(tableName, "indexed_hash")
	_searchIndexState.IndexStatus = field.NewString(tableName, "index_status")
	_searchIndexState.LastIndexedAt = field.NewTime(tableName, "last_indexed_at")
	_searchIndexState.LastError = field.NewString(tableName, "last_error")
	_searchIndexState.RetryCount = field.NewInt(tableName, "retry_count")
	_searchIndexState.CreatedAt = field.NewTime(tableName, "created_at")
	_searchIndexState.UpdatedAt = field.NewTime(tableName, "updated_at")

	_searchIndexState.fillFieldMap()

	return _searchIndexState
}

type searchIndexState struct {
	searchIndexStateDo searchIndexStateDo

	ALL           field.Asterisk
	ObjectType    field.String
	ObjectID      field.String
	ContentHash   field.String
	IndexedHash   field.String
	IndexStatus   field.String
	LastIndexedAt field.Time
	LastError     field.String
	RetryCount    field.Int
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (s searchIndexState) Table(newTableName string) *searchIndexState {
	s.searchIndexStateDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s searchIndexState) As(alias string) *searchIndexState {
	s.searchIndexStateDo.DO = *(s.searchIndexStateDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *searchIndexState) updateTableName(table string) *searchIndexState {
	s.ALL = field.NewAsterisk(table)
	s.ObjectType = field.NewString(table, "object_type")
	s.ObjectID = field.NewString(table, "object_id")
	s.ContentHash = field.NewString(table, "content_hash")
	s.IndexedHash = field.NewString(table, "indexed_hash")
	s.IndexStatus = field.NewString(table, "index_status")
	s.LastIndexedAt = field.NewTime(table, "last_indexed_at")
	s.LastError = field.NewString(table, "last_error")
	s.RetryCount = field.NewInt(table, "retry_count")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *searchIndexState) WithContext(ctx context.Context) ISearchIndexStateDo {
	return s.searchIndexStateDo.WithContext(ctx)
}

func (s searchIndexState) TableName() string { return s.searchIndexStateDo.TableName() }

func (s searchIndexState) Alias() string { return s.searchIndexStateDo.Alias() }

func (s searchIndexState) Columns(cols ...field.Expr) gen.Columns {
	return s.searchIndexStateDo.Columns(cols...)
}

func (s *searchIndexState) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *searchIndexState) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["object_type"] = s.ObjectType
	s.fieldMap["object_id"] = s.ObjectID
	s.fieldMap["content_hash"] = s.ContentHash
	s.fieldMap["indexed_hash"] = s.IndexedHash
	s.fieldMap["index_status"] = s.IndexStatus
	s.fieldMap["last_indexed_at"] = s.LastIndexedAt
	s.fieldMap["last_error"] = s.LastError
	s.fieldMap["retry_count"] = s.RetryCount
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s searchIndexState) clone(db *gorm.DB) searchIndexState {
	s.searchIndexStateDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s searchIndexState) replaceDB(db *gorm.DB) searchIndexState {
	s.searchIndexStateDo.ReplaceDB(db)
	return s
}

type searchIndexStateDo struct{ gen.DO }

type ISearchIndexStateDo interface {
	gen.SubQuery
	Debug() ISearchIndexStateDo
	WithContext(ctx context.Context) ISearchIndexStateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISearchIndexStateDo
	WriteDB() ISearchIndexStateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISearchIndexStateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISearchIndexStateDo
	Not(conds ...gen.Condition) ISearchIndexStateDo
	Or(conds ...gen.Condition) ISearchIndexStateDo
	Select(conds ...field.Expr) ISearchIndexStateDo
	Where(conds ...gen.Condition) ISearchIndexStateDo
	Order(conds ...field.Expr) ISearchIndexStateDo
	Distinct(cols ...field.Expr) ISearchIndexStateDo
	Omit(cols ...field.Expr) ISearchIndexStateDo
	Join(table schema.Tabler, on ...field.Expr) ISearchIndexStateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISearchIndexStateDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISearchIndexStateDo
	Group(cols ...field.Expr) ISearchIndexStateDo
	Having(conds ...gen.Condition) ISearchIndexStateDo
	Limit(limit int) ISearchIndexStateDo
	Offset(offset int) ISearchIndexStateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISearchIndexStateDo
	Unscoped() ISearchIndexStateDo
	Create(values ...*models.SearchIndexState) error
	CreateInBatches(values []*models.SearchIndexState, batchSize int) error
	Save(values ...*models.SearchIndexState) error
	First() (*models.SearchIndexState, error)
	Take() (*models.SearchIndexState, error)
	Last() (*models.SearchIndexState, error)
	Find() ([]*models.SearchIndexState, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SearchIndexState, err error)
	FindInBatches(result *[]*models.SearchIndexState, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SearchIndexState) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISearchIndexStateDo
	Assign(attrs ...field.AssignExpr) ISearchIndexStateDo
	Joins(fields ...field.RelationField) ISearchIndexStateDo
	Preload(fields ...field.RelationField) ISearchIndexStateDo
	FirstOrInit() (*models.SearchIndexState, error)
	FirstOrCreate() (*models.SearchIndexState, error)
	FindByPage(offset int, limit int) (result []*models.SearchIndexState, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISearchIndexStateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s searchIndexStateDo) Debug() ISearchIndexStateDo {
	return s.withDO(s.DO.Debug())
}

func (s searchIndexStateDo) WithContext(ctx context.Context) ISearchIndexStateDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s searchIndexStateDo) ReadDB() ISearchIndexStateDo {
	return s.Clauses(dbresolver.Read)
}

func (s searchIndexStateDo) WriteDB() ISearchIndexStateDo {
	return s.Clauses(dbresolver.Write)
}

func (s searchIndexStateDo) Session(config *gorm.Session) ISearchIndexStateDo {
	return s.withDO(s.DO.Session(config))
}

func (s searchIndexStateDo) Clauses(conds ...clause.Expression) ISearchIndexStateDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s searchIndexStateDo) Returning(value interface{}, columns ...string) ISearchIndexStateDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s searchIndexStateDo) Not(conds ...gen.Condition) ISearchIndexStateDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s searchIndexStateDo) Or(conds ...gen.Condition) ISearchIndexStateDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s searchIndexStateDo) Select(conds ...field.Expr) ISearchIndexStateDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s searchIndexStateDo) Where(conds ...gen.Condition) ISearchIndexStateDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s searchIndexStateDo) Order(conds ...field.Expr) ISearchIndexStateDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s searchIndexStateDo) Distinct(cols ...field.Expr) ISearchIndexStateDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s searchIndexStateDo) Omit(cols ...field.Expr) ISearchIndexStateDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s searchIndexStateDo) Join(table schema.Tabler, on ...field.Expr) ISearchIndexStateDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s searchIndexStateDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISearchIndexStateDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s searchIndexStateDo) RightJoin(table schema.Tabler, on ...field.Expr) ISearchIndexStateDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s searchIndexStateDo) Group(cols ...field.Expr) ISearchIndexStateDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s searchIndexStateDo) Having(conds ...gen.Condition) ISearchIndexStateDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s searchIndexStateDo) Limit(limit int) ISearchIndexStateDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s searchIndexStateDo) Offset(offset int) ISearchIndexStateDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s searchIndexStateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISearchIndexStateDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s searchIndexStateDo) Unscoped() ISearchIndexStateDo {
	return s.withDO(s.DO.Unscoped())
}

func (s searchIndexStateDo) Create(values ...*models.SearchIndexState) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s searchIndexStateDo) CreateInBatches(values []*models.SearchIndexState, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s searchIndexStateDo) Save(values ...*models.SearchIndexState) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s searchIndexStateDo) First() (*models.SearchIndexState, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SearchIndexState), nil
	}
}

func (s searchIndexStateDo) Take() (*models.SearchIndexState, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SearchIndexState), nil
	}
}

func (s searchIndexStateDo) Last() (*models.SearchIndexState, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SearchIndexState), nil
	}
}

func (s searchIndexStateDo) Find() ([]*models.SearchIndexState, error) {
	result, err := s.DO.Find()
	return result.([]*models.SearchIndexState), err
}

func (s searchIndexStateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SearchIndexState, err error) {
	buf := make([]*models.SearchIndexState, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s searchIndexStateDo) FindInBatches(result *[]*models.SearchIndexState, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s searchIndexStateDo) Attrs(attrs ...field.AssignExpr) ISearchIndexStateDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s searchIndexStateDo) Assign(attrs ...field.AssignExpr) ISearchIndexStateDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s searchIndexStateDo) Joins(fields ...field.RelationField) ISearchIndexStateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s searchIndexStateDo) Preload(fields ...field.RelationField) ISearchIndexStateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s searchIndexStateDo) FirstOrInit() (*models.SearchIndexState, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SearchIndexState), nil
	}
}

func (s searchIndexStateDo) FirstOrCreate() (*models.SearchIndexState, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SearchIndexState), nil
	}
}

func (s searchIndexStateDo) FindByPage(offset int, limit int) (result []*models.SearchIndexState, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s searchIndexStateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s searchIndexStateDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s searchIndexStateDo) Delete(models ...*models.SearchIndexState) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *searchIndexStateDo) withDO(do gen.Dao) *searchIndexStateDo {
	s.DO = *do.(*gen.DO)
	return s
}
