// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kmemo/internal/storage/models"
)

func newSourceDocument(db *gorm.DB, opts ...gen.DOOption) sourceDocument {
	_sourceDocument := sourceDocument{}

	_sourceDocument.sourceDocumentDo.UseDB(db, opts...)
	_sourceDocument.sourceDocumentDo.UseModel(&models.SourceDocument{})

	tableName := _sourceDocument.sourceDocumentDo.TableName()
	_sourceDocument.ALL = field.NewAsterisk(tableName)
	_sourceDocument.ID = field.NewString(tableName, "id")
	_sourceDocument.KnowledgeID = field.NewString(tableName, "knowledge_id")
	_sourceDocument.SourceType = field.NewString(tableName, "source_type")
	_sourceDocument.Title = field.NewString(tableName, "title")
	_sourceDocument.Author = field.NewString(tableName, "author")
	_sourceDocument.OriginalURI = field.NewString(tableName, "original_uri")
	_sourceDocument.OriginalHash = field.NewString(tableName, "original_hash")
	_sourceDocument.Slug = field.NewString(tableName, "slug")
	_sourceDocument.Ext = field.NewString(tableName, "ext")
	_sourceDocument.CreatedAt = field.NewTime(tableName, "created_at")
	_sourceDocument.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sourceDocument.Cards = sourceDocumentHasManyCards{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Cards", "models.Card"),
		Knowledge: struct {
			field.RelationField
			Parent struct {
				field.RelationField
			}
			FSRSPreset struct {
				field.RelationField
			}
			Children struct {
				field.RelationField
			}
			SourceDocuments struct {
				field.RelationField
				Knowledge struct {
					field.RelationField
				}
				Cards struct {
					field.RelationField
				}
			}
			Cards struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Cards.Knowledge", "models.Knowledge"),
			Parent: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Cards.Knowledge.Parent", "models.Knowledge"),
			},
			FSRSPreset: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Cards.Knowledge.FSRSPreset", "models.FSRSParameter"),
			},
			Children: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Cards.Knowledge.Children", "models.Knowledge"),
			},
			SourceDocuments: struct {
				field.RelationField
				Knowledge struct {
					field.RelationField
				}
				Cards struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Cards.Knowledge.SourceDocuments", "models.SourceDocument"),
				Knowledge: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Cards.Knowledge.SourceDocuments.Knowledge", "models.Knowledge"),
				},
				Cards: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Cards.Knowledge.SourceDocuments.Cards", "models.Card"),
				},
			},
			Cards: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Cards.Knowledge.Cards", "models.Card"),
			},
		},
		SourceDocument: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Cards.SourceDocument", "models.SourceDocument"),
		},
		Parent: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Cards.Parent", "models.Card"),
		},
		CoverAsset: struct {
			field.RelationField
			Card struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Cards.CoverAsset", "models.Asset"),
			Card: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Cards.CoverAsset.Card", "models.Card"),
			},
		},
		SRS: struct {
			field.RelationField
			Card struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Cards.SRS", "models.CardSRS"),
			Card: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Cards.SRS.Card", "models.Card"),
			},
		},
		Children: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Cards.Children", "models.Card"),
		},
		Assets: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Cards.Assets", "models.Asset"),
		},
		CardTags: struct {
			field.RelationField
			Card struct {
				field.RelationField
			}
			Tag struct {
				field.RelationField
				CardTags struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Cards.CardTags", "models.CardTag"),
			Card: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Cards.CardTags.Card", "models.Card"),
			},
			Tag: struct {
				field.RelationField
				CardTags struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Cards.CardTags.Tag", "models.Tag"),
				CardTags: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Cards.CardTags.Tag.CardTags", "models.CardTag"),
				},
			},
		},
	}

	_sourceDocument.Knowledge = sourceDocumentBelongsToKnowledge{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Knowledge", "models.Knowledge"),
	}

	_sourceDocument.fillFieldMap()

	return _sourceDocument
}

type sourceDocument struct {
	sourceDocumentDo sourceDocumentDo

	ALL          field.Asterisk
	ID           field.String
	KnowledgeID  field.String
	SourceType   field.String
	Title        field.String
	Author       field.String
	OriginalURI  field.String
	OriginalHash field.String
	Slug         field.String
	Ext          field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time
	Cards        sourceDocumentHasManyCards

	Knowledge sourceDocumentBelongsToKnowledge

	fieldMap map[string]field.Expr
}

func (s sourceDocument) Table(newTableName string) *sourceDocument {
	s.sourceDocumentDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sourceDocument) As(alias string) *sourceDocument {
	s.sourceDocumentDo.DO = *(s.sourceDocumentDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sourceDocument) updateTableName(table string) *sourceDocument {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.KnowledgeID = field.NewString(table, "knowledge_id")
	s.SourceType = field.NewString(table, "source_type")
	s.Title = field.NewString(table, "title")
	s.Author = field.NewString(table, "author")
	s.OriginalURI = field.NewString(table, "original_uri")
	s.OriginalHash = field.NewString(table, "original_hash")
	s.Slug = field.NewString(table, "slug")
	s.Ext = field.NewString(table, "ext")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *sourceDocument) WithContext(ctx context.Context) ISourceDocumentDo {
	return s.sourceDocumentDo.WithContext(ctx)
}

func (s sourceDocument) TableName() string { return s.sourceDocumentDo.TableName() }

func (s sourceDocument) Alias() string { return s.sourceDocumentDo.Alias() }

func (s sourceDocument) Columns(cols ...field.Expr) gen.Columns {
	return s.sourceDocumentDo.Columns(cols...)
}

func (s *sourceDocument) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sourceDocument) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 13)
	s.fieldMap["id"] = s.ID
	s.fieldMap["knowledge_id"] = s.KnowledgeID
	s.fieldMap["source_type"] = s.SourceType
	s.fieldMap["title"] = s.Title
	s.fieldMap["author"] = s.Author
	s.fieldMap["original_uri"] = s.OriginalURI
	s.fieldMap["original_hash"] = s.OriginalHash
	s.fieldMap["slug"] = s.Slug
	s.fieldMap["ext"] = s.Ext
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt

}

func (s sourceDocument) clone(db *gorm.DB) sourceDocument {
	s.sourceDocumentDo.ReplaceConnPool(db.Statement.ConnPool)
	s.Cards.db = db.Session(&gorm.Session{Initialized: true})
	s.Cards.db.Statement.ConnPool = db.Statement.ConnPool
	s.Knowledge.db = db.Session(&gorm.Session{Initialized: true})
	s.Knowledge.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sourceDocument) replaceDB(db *gorm.DB) sourceDocument {
	s.sourceDocumentDo.ReplaceDB(db)
	s.Cards.db = db.Session(&gorm.Session{})
	s.Knowledge.db = db.Session(&gorm.Session{})
	return s
}

type sourceDocumentHasManyCards struct {
	db *gorm.DB

	field.RelationField

	Knowledge struct {
		field.RelationField
		Parent struct {
			field.RelationField
		}
		FSRSPreset struct {
			field.RelationField
		}
		Children struct {
			field.RelationField
		}
		SourceDocuments struct {
			field.RelationField
			Knowledge struct {
				field.RelationField
			}
			Cards struct {
				field.RelationField
			}
		}
		Cards struct {
			field.RelationField
		}
	}
	SourceDocument struct {
		field.RelationField
	}
	Parent struct {
		field.RelationField
	}
	CoverAsset struct {
		field.RelationField
		Card struct {
			field.RelationField
		}
	}
	SRS struct {
		field.RelationField
		Card struct {
			field.RelationField
		}
	}
	Children struct {
		field.RelationField
	}
	Assets struct {
		field.RelationField
	}
	CardTags struct {
		field.RelationField
		Card struct {
			field.RelationField
		}
		Tag struct {
			field.RelationField
			CardTags struct {
				field.RelationField
			}
		}
	}
}

func (a sourceDocumentHasManyCards) Where(conds ...field.Expr) *sourceDocumentHasManyCards {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sourceDocumentHasManyCards) WithContext(ctx context.Context) *sourceDocumentHasManyCards {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sourceDocumentHasManyCards) Session(session *gorm.Session) *sourceDocumentHasManyCards {
	a.db = a.db.Session(session)
	return &a
}

func (a sourceDocumentHasManyCards) Model(m *models.SourceDocument) *sourceDocumentHasManyCardsTx {
	return &sourceDocumentHasManyCardsTx{a.db.Model(m).Association(a.Name())}
}

func (a sourceDocumentHasManyCards) Unscoped() *sourceDocumentHasManyCards {
	a.db = a.db.Unscoped()
	return &a
}

type sourceDocumentHasManyCardsTx struct{ tx *gorm.Association }

func (a sourceDocumentHasManyCardsTx) Find() (result []*models.Card, err error) {
	return result, a.tx.Find(&result)
}

func (a sourceDocumentHasManyCardsTx) Append(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sourceDocumentHasManyCardsTx) Replace(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sourceDocumentHasManyCardsTx) Delete(values ...*models.Card) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sourceDocumentHasManyCardsTx) Clear() error {
	return a.tx.Clear()
}

func (a sourceDocumentHasManyCardsTx) Count() int64 {
	return a.tx.Count()
}

func (a sourceDocumentHasManyCardsTx) Unscoped() *sourceDocumentHasManyCardsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sourceDocumentBelongsToKnowledge struct {
	db *gorm.DB

	field.RelationField
}

func (a sourceDocumentBelongsToKnowledge) Where(conds ...field.Expr) *sourceDocumentBelongsToKnowledge {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sourceDocumentBelongsToKnowledge) WithContext(ctx context.Context) *sourceDocumentBelongsToKnowledge {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sourceDocumentBelongsToKnowledge) Session(session *gorm.Session) *sourceDocumentBelongsToKnowledge {
	a.db = a.db.Session(session)
	return &a
}

func (a sourceDocumentBelongsToKnowledge) Model(m *models.SourceDocument) *sourceDocumentBelongsToKnowledgeTx {
	return &sourceDocumentBelongsToKnowledgeTx{a.db.Model(m).Association(a.Name())}
}

func (a sourceDocumentBelongsToKnowledge) Unscoped() *sourceDocumentBelongsToKnowledge {
	a.db = a.db.Unscoped()
	return &a
}

type sourceDocumentBelongsToKnowledgeTx struct{ tx *gorm.Association }

func (a sourceDocumentBelongsToKnowledgeTx) Find() (result *models.Knowledge, err error) {
	return result, a.tx.Find(&result)
}

func (a sourceDocumentBelongsToKnowledgeTx) Append(values ...*models.Knowledge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sourceDocumentBelongsToKnowledgeTx) Replace(values ...*models.Knowledge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sourceDocumentBelongsToKnowledgeTx) Delete(values ...*models.Knowledge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sourceDocumentBelongsToKnowledgeTx) Clear() error {
	return a.tx.Clear()
}

func (a sourceDocumentBelongsToKnowledgeTx) Count() int64 {
	return a.tx.Count()
}

func (a sourceDocumentBelongsToKnowledgeTx) Unscoped() *sourceDocumentBelongsToKnowledgeTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sourceDocumentDo struct{ gen.DO }

type ISourceDocumentDo interface {
	gen.SubQuery
	Debug() ISourceDocumentDo
	WithContext(ctx context.Context) ISourceDocumentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISourceDocumentDo
	WriteDB() ISourceDocumentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISourceDocumentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISourceDocumentDo
	Not(conds ...gen.Condition) ISourceDocumentDo
	Or(conds ...gen.Condition) ISourceDocumentDo
	Select(conds ...field.Expr) ISourceDocumentDo
	Where(conds ...gen.Condition) ISourceDocumentDo
	Order(conds ...field.Expr) ISourceDocumentDo
	Distinct(cols ...field.Expr) ISourceDocumentDo
	Omit(cols ...field.Expr) ISourceDocumentDo
	Join(table schema.Tabler, on ...field.Expr) ISourceDocumentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISourceDocumentDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISourceDocumentDo
	Group(cols ...field.Expr) ISourceDocumentDo
	Having(conds ...gen.Condition) ISourceDocumentDo
	Limit(limit int) ISourceDocumentDo
	Offset(offset int) ISourceDocumentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISourceDocumentDo
	Unscoped() ISourceDocumentDo
	Create(values ...*models.SourceDocument) error
	CreateInBatches(values []*models.SourceDocument, batchSize int) error
	Save(values ...*models.SourceDocument) error
	First() (*models.SourceDocument, error)
	Take() (*models.SourceDocument, error)
	Last() (*models.SourceDocument, error)
	Find() ([]*models.SourceDocument, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SourceDocument, err error)
	FindInBatches(result *[]*models.SourceDocument, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SourceDocument) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISourceDocumentDo
	Assign(attrs ...field.AssignExpr) ISourceDocumentDo
	Joins(fields ...field.RelationField) ISourceDocumentDo
	Preload(fields ...field.RelationField) ISourceDocumentDo
	FirstOrInit() (*models.SourceDocument, error)
	FirstOrCreate() (*models.SourceDocument, error)
	FindByPage(offset int, limit int) (result []*models.SourceDocument, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISourceDocumentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sourceDocumentDo) Debug() ISourceDocumentDo {
	return s.withDO(s.DO.Debug())
}

func (s sourceDocumentDo) WithContext(ctx context.Context) ISourceDocumentDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sourceDocumentDo) ReadDB() ISourceDocumentDo {
	return s.Clauses(dbresolver.Read)
}

func (s sourceDocumentDo) WriteDB() ISourceDocumentDo {
	return s.Clauses(dbresolver.Write)
}

func (s sourceDocumentDo) Session(config *gorm.Session) ISourceDocumentDo {
	return s.withDO(s.DO.Session(config))
}

func (s sourceDocumentDo) Clauses(conds ...clause.Expression) ISourceDocumentDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sourceDocumentDo) Returning(value interface{}, columns ...string) ISourceDocumentDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sourceDocumentDo) Not(conds ...gen.Condition) ISourceDocumentDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sourceDocumentDo) Or(conds ...gen.Condition) ISourceDocumentDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sourceDocumentDo) Select(conds ...field.Expr) ISourceDocumentDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sourceDocumentDo) Where(conds ...gen.Condition) ISourceDocumentDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sourceDocumentDo) Order(conds ...field.Expr) ISourceDocumentDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sourceDocumentDo) Distinct(cols ...field.Expr) ISourceDocumentDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sourceDocumentDo) Omit(cols ...field.Expr) ISourceDocumentDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sourceDocumentDo) Join(table schema.Tabler, on ...field.Expr) ISourceDocumentDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sourceDocumentDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISourceDocumentDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sourceDocumentDo) RightJoin(table schema.Tabler, on ...field.Expr) ISourceDocumentDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sourceDocumentDo) Group(cols ...field.Expr) ISourceDocumentDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sourceDocumentDo) Having(conds ...gen.Condition) ISourceDocumentDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sourceDocumentDo) Limit(limit int) ISourceDocumentDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sourceDocumentDo) Offset(offset int) ISourceDocumentDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sourceDocumentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISourceDocumentDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sourceDocumentDo) Unscoped() ISourceDocumentDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sourceDocumentDo) Create(values ...*models.SourceDocument) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sourceDocumentDo) CreateInBatches(values []*models.SourceDocument, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sourceDocumentDo) Save(values ...*models.SourceDocument) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sourceDocumentDo) First() (*models.SourceDocument, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SourceDocument), nil
	}
}

func (s sourceDocumentDo) Take() (*models.SourceDocument, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SourceDocument), nil
	}
}

func (s sourceDocumentDo) Last() (*models.SourceDocument, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SourceDocument), nil
	}
}

func (s sourceDocumentDo) Find() ([]*models.SourceDocument, error) {
	result, err := s.DO.Find()
	return result.([]*models.SourceDocument), err
}

func (s sourceDocumentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SourceDocument, err error) {
	buf := make([]*models.SourceDocument, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sourceDocumentDo) FindInBatches(result *[]*models.SourceDocument, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sourceDocumentDo) Attrs(attrs ...field.AssignExpr) ISourceDocumentDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sourceDocumentDo) Assign(attrs ...field.AssignExpr) ISourceDocumentDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sourceDocumentDo) Joins(fields ...field.RelationField) ISourceDocumentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sourceDocumentDo) Preload(fields ...field.RelationField) ISourceDocumentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sourceDocumentDo) FirstOrInit() (*models.SourceDocument, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SourceDocument), nil
	}
}

func (s sourceDocumentDo) FirstOrCreate() (*models.SourceDocument, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SourceDocument), nil
	}
}

func (s sourceDocumentDo) FindByPage(offset int, limit int) (result []*models.SourceDocument, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sourceDocumentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sourceDocumentDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sourceDocumentDo) Delete(models ...*models.SourceDocument) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sourceDocumentDo) withDO(do gen.Dao) *sourceDocumentDo {
	s.DO = *do.(*gen.DO)
	return s
}
