import { COMMAND_IDS } from '@/shared/constants/commands'
import type { CommandItem } from '../types'

export const COMMAND_REGISTRY: CommandItem[] = [
  {
    id: COMMAND_IDS.goInbox,
    title: 'Go to Inbox',
    subtitle: 'Switch workspace to inbox context',
    group: 'navigation',
    keywords: ['inbox', 'queue', 'navigation', 'go-inbox'],
    shortcut: ['Alt+1'],
  },
  {
    id: COMMAND_IDS.captureBlankArticle,
    title: 'Create Blank Article',
    subtitle: 'Open capture dialog · blank note',
    group: 'capture',
    keywords: ['capture', 'blank', 'inbox', 'new', 'article'],
  },
  {
    id: COMMAND_IDS.capturePasteText,
    title: 'Paste Text Capture',
    subtitle: 'Open capture dialog · paste text',
    group: 'capture',
    keywords: ['capture', 'paste', 'text', 'clipboard', 'inbox'],
  },
  {
    id: COMMAND_IDS.captureUrl,
    title: 'Capture from URL',
    subtitle: 'Open capture dialog · URL placeholder',
    group: 'capture',
    keywords: ['capture', 'url', 'link', 'web', 'inbox'],
  },
  {
    id: COMMAND_IDS.createNode,
    title: 'Create Node',
    subtitle: 'Open create dialog · knowledge topic node',
    group: 'knowledge',
    keywords: ['create', 'node', 'topic', 'tree', 'knowledge'],
  },
  {
    id: COMMAND_IDS.createCard,
    title: 'Create Card',
    subtitle: 'Open create dialog · knowledge card',
    group: 'knowledge',
    keywords: ['create', 'card', 'tree', 'knowledge', 'review'],
  },
  {
    id: COMMAND_IDS.createManualExtract,
    title: 'Create Manual Extract',
    subtitle: 'Open create dialog · manual extract',
    group: 'knowledge',
    keywords: ['create', 'extract', 'manual', 'quote', 'knowledge'],
  },
  {
    id: COMMAND_IDS.goReading,
    title: 'Go to Reading',
    subtitle: 'Switch workspace to reading context',
    group: 'navigation',
    keywords: ['reading', 'article', 'navigation'],
    shortcut: ['Alt+2', 'g r'],
  },
  {
    id: COMMAND_IDS.goKnowledge,
    title: 'Go to Knowledge',
    subtitle: 'Switch workspace to knowledge context',
    group: 'navigation',
    keywords: ['knowledge', 'tree', 'navigation'],
    shortcut: ['Alt+3', 'g k'],
  },
  {
    id: COMMAND_IDS.goReview,
    title: 'Go to Review',
    subtitle: 'Switch workspace to review context',
    group: 'navigation',
    keywords: ['review', 'queue', 'navigation'],
    shortcut: ['Alt+4', 'g v'],
  },
  {
    id: COMMAND_IDS.goSearch,
    title: 'Go to Search',
    subtitle: 'Switch workspace to search context',
    group: 'navigation',
    keywords: ['search', 'navigation'],
    shortcut: ['Alt+5'],
  },
  {
    id: COMMAND_IDS.focusSearch,
    title: 'Focus Search',
    subtitle: 'Open search workspace quickly',
    group: 'focus',
    keywords: ['focus', 'search'],
    shortcut: ['Cmd/Ctrl+F'],
  },
  {
    id: COMMAND_IDS.openFirstReviewItem,
    title: 'Open First Review Item',
    subtitle: 'Open first available item in review queue',
    group: 'review',
    keywords: ['review', 'first', 'open'],
    shortcut: ['Cmd/Ctrl+Shift+R'],
  },
  {
    id: COMMAND_IDS.openSelectedArticle,
    title: 'Open Selected Article',
    subtitle: 'Open current selected article in reading editor',
    group: 'reading',
    keywords: ['open', 'article', 'reader'],
  },
  {
    id: COMMAND_IDS.createExtract,
    title: 'Create Extract',
    subtitle: 'Create extract from current editor selection',
    group: 'extract',
    keywords: ['extract', 'selection', 'quote'],
  },
  {
    id: COMMAND_IDS.openSelectedExtract,
    title: 'Open Selected Extract',
    subtitle: 'Open current selected extract detail panel',
    group: 'extract',
    keywords: ['extract', 'open', 'detail'],
  },
  {
    id: COMMAND_IDS.backToSourceArticle,
    title: 'Back to Source Article',
    subtitle: 'Jump from selected extract back to source article',
    group: 'extract',
    keywords: ['source', 'article', 'back'],
  },
  {
    id: COMMAND_IDS.revealCurrentExtractInTree,
    title: 'Reveal Current Extract in Tree',
    subtitle: 'Switch to knowledge and select extract node',
    group: 'knowledge',
    keywords: ['reveal', 'tree', 'extract'],
  },
  {
    id: COMMAND_IDS.addCurrentCardToReview,
    title: 'Add Current Card to Review',
    subtitle: 'Create a review item from the selected knowledge card',
    group: 'review',
    keywords: ['card', 'review', 'add', 'knowledge'],
  },
  {
    id: COMMAND_IDS.openCurrentCardReview,
    title: 'Open Current Card Review',
    subtitle: 'Jump to the review item linked to the selected card',
    group: 'review',
    keywords: ['card', 'review', 'open', 'knowledge'],
  },
  {
    id: COMMAND_IDS.addCurrentExtractToReview,
    title: 'Add Current Extract to Review',
    subtitle: 'Create a review item from the current extract',
    group: 'review',
    keywords: ['extract', 'review', 'add'],
  },
  {
    id: COMMAND_IDS.openCurrentExtractReview,
    title: 'Open Current Extract Review',
    subtitle: 'Jump to the review item linked to the current extract',
    group: 'review',
    keywords: ['extract', 'review', 'open'],
  },
  {
    id: COMMAND_IDS.toggleCommandPalette,
    title: 'Toggle Command Palette',
    subtitle: 'Open or close command palette',
    group: 'system',
    keywords: ['command', 'palette'],
    shortcut: ['Cmd/Ctrl+K'],
  },
  {
    id: COMMAND_IDS.closeCommandPalette,
    title: 'Close Command Palette',
    subtitle: 'Close command palette if open',
    group: 'system',
    keywords: ['close', 'palette', 'escape'],
    shortcut: ['Esc'],
  },
]
